(module
  ;; EntryJS Compiled Project
  ;; Generated by EntryJS-to-WASM Compiler
  ;; 
  ;; Memory Layout:
  ;; - 0-63: System state (frame count, time, mouse, keys, etc.)
  ;; - 64-1023: Reserved
  ;; - 1024+: Entity data (64 bytes each)
  ;; - After entities: Variables (8 bytes each)


  ;; ===== IMPORTS =====
  ;; Math functions from JS
  (import "math" "sin" (func $sin (param f64) (result f64)))
  (import "math" "cos" (func $cos (param f64) (result f64)))
  (import "math" "sqrt" (func $sqrt (param f64) (result f64)))
  (import "math" "random" (func $random (result f64)))
  (import "math" "floor" (func $floor (param f64) (result f64)))
  (import "math" "ceil" (func $ceil (param f64) (result f64)))
  (import "math" "abs" (func $abs (param f64) (result f64)))
  (import "math" "atan2" (func $atan2 (param f64 f64) (result f64)))
  (import "math" "asin" (func $asin (param f64) (result f64)))
  (import "math" "acos" (func $acos (param f64) (result f64)))
  (import "math" "atan" (func $atan (param f64) (result f64)))
  (import "math" "log" (func $mathLog (param f64) (result f64)))
  (import "math" "exp" (func $exp (param f64) (result f64)))
  (import "math" "pow" (func $pow (param f64 f64) (result f64)))
  
  ;; System callbacks
  (import "system" "log" (func $sysLog (param f64)))
  (import "system" "playSound" (func $playSound (param i32 i32)))
  
  ;; Timer functions
  (import "timer" "getProjectTimer" (func $getProjectTimer (result f64)))
  (import "timer" "startProjectTimer" (func $startProjectTimer))
  (import "timer" "stopProjectTimer" (func $stopProjectTimer))
  (import "timer" "resetProjectTimer" (func $resetProjectTimer))
  (import "timer" "setProjectTimerVisible" (func $setProjectTimerVisible (param i32)))
  
  ;; Answer/Input functions
  (import "input" "askAndWait" (func $askAndWait (param i32)))
  (import "input" "getAnswer" (func $getAnswer (result f64)))
  (import "input" "setAnswerVisible" (func $setAnswerVisible (param i32)))
  
  ;; Clone functions
  (import "clone" "createClone" (func $createClone (param i32)))
  (import "clone" "deleteClone" (func $deleteClone (param i32)))
  (import "clone" "removeAllClones" (func $removeAllClones))
  
  ;; Sound functions
  (import "sound" "playSoundAndWait" (func $playSoundAndWait (param i32 i32)))
  (import "sound" "playSoundForSeconds" (func $playSoundForSeconds (param i32 i32 f64)))
  (import "sound" "playSoundFromTo" (func $playSoundFromTo (param i32 i32 f64 f64)))
  (import "sound" "changeSoundVolume" (func $changeSoundVolume (param i32 f64)))
  (import "sound" "setSoundVolume" (func $setSoundVolume (param i32 f64)))
  (import "sound" "getSoundVolume" (func $getSoundVolume (param i32) (result f64)))
  (import "sound" "changeSoundSpeed" (func $changeSoundSpeed (param i32 f64)))
  (import "sound" "setSoundSpeed" (func $setSoundSpeed (param i32 f64)))
  (import "sound" "getSoundSpeed" (func $getSoundSpeed (param i32) (result f64)))
  (import "sound" "playBGM" (func $playBGM (param i32 i32)))
  (import "sound" "stopBGM" (func $stopBGM))
  (import "sound" "stopAllSounds" (func $stopAllSounds))
  
  ;; Dialog functions
  (import "dialog" "showDialog" (func $showDialog (param i32 i32)))
  (import "dialog" "hideDialog" (func $hideDialog (param i32)))
  (import "dialog" "sendMessageAndWait" (func $sendMessageAndWait (param i32)))
  
  ;; Brush/Drawing functions (implemented in JS renderer for performance)
  (import "brush" "startDrawing" (func $startDrawing (param i32)))
  (import "brush" "stopDrawing" (func $stopDrawing (param i32)))
  (import "brush" "stamp" (func $stamp (param i32)))
  (import "brush" "clearBrush" (func $clearBrush))
  ;; Note: setBrushColor and setRandomBrushColor are now internal WASM functions
  ;; Colors are stored in entity memory and read by JS renderer
  (import "brush" "changeBrushThickness" (func $changeBrushThickness (param i32 f64)))
  (import "brush" "setBrushThickness" (func $setBrushThickness (param i32 f64)))
  (import "brush" "changeBrushTransparency" (func $changeBrushTransparency (param i32 f64)))
  (import "brush" "setBrushTransparency" (func $setBrushTransparency (param i32 f64)))
  (import "brush" "startFill" (func $startFill (param i32)))
  (import "brush" "stopFill" (func $stopFill (param i32)))
  ;; Note: setFillColor is now internal - colors stored in entity memory
  (import "brush" "notifyPosition" (func $brushNotifyPosition (param i32 f64 f64)))


  ;; ===== MEMORY =====
  (memory (export "memory") 250)
  
  ;; System state offsets
  ;; 0: frame count (i32)
  ;; 4: running (i32)
  ;; 8: current time ms (f64)
  ;; 16: mouse x (f64)
  ;; 24: mouse y (f64)
  ;; 32: mouse clicked (i32)
  ;; 36: key states base (64 bytes for 512 keys as bits)


  ;; ===== GLOBALS =====
  (global $frameCount (mut i32) (i32.const 0))
  (global $running (mut i32) (i32.const 0))
  (global $deltaTime (mut f64) (f64.const 0.016666))
  (global $currentEntityIndex (mut i32) (i32.const 0))
  (global $currentScene (mut i32) (i32.const 0))
  (global $sceneCount (mut i32) (i32.const 1))
  (global $sceneJustChanged (mut i32) (i32.const 0))
  (global $prevMouseClicked (mut i32) (i32.const 0))
  (global $clickedEntityIndex (mut i32) (i32.const -1))
  (global $msg_flag_0 (mut i32) (i32.const 0)) ;; message: 신호
  (global $var_visible_0 (mut i32) (i32.const 1)) ;; 변수
  (global $var_visible_1 (mut i32) (i32.const 0)) ;; 초시계
  (global $var_visible_2 (mut i32) (i32.const 0)) ;; 대답
  (global $list_visible_0 (mut i32) (i32.const 1)) ;; 리스트
  (global $dialog_type_0 (mut i32) (i32.const 0))
  (global $dialog_text_ptr_0 (mut i32) (i32.const 0))
  (global $str_pool_ptr (mut i32) (i32.const 16001192))
  (global $thread_0_pc (mut i32) (i32.const 0))
  (global $thread_0_waiting (mut f64) (f64.const 0))
  (global $thread_0_active (mut i32) (i32.const 0))
  (global $thread_0_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_0_resumeDepth (mut i32) (i32.const 0))
  (global $thread_1_pc (mut i32) (i32.const 0))
  (global $thread_1_waiting (mut f64) (f64.const 0))
  (global $thread_1_active (mut i32) (i32.const 0))
  (global $thread_1_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_1_resumeDepth (mut i32) (i32.const 0))
  (global $thread_2_pc (mut i32) (i32.const 0))
  (global $thread_2_waiting (mut f64) (f64.const 0))
  (global $thread_2_active (mut i32) (i32.const 0))
  (global $thread_2_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_2_resumeDepth (mut i32) (i32.const 0))
  (global $thread_3_pc (mut i32) (i32.const 0))
  (global $thread_3_waiting (mut f64) (f64.const 0))
  (global $thread_3_active (mut i32) (i32.const 0))
  (global $thread_3_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_3_resumeDepth (mut i32) (i32.const 0))
  (global $thread_4_pc (mut i32) (i32.const 0))
  (global $thread_4_waiting (mut f64) (f64.const 0))
  (global $thread_4_active (mut i32) (i32.const 0))
  (global $thread_4_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_4_resumeDepth (mut i32) (i32.const 0))
  (global $thread_5_pc (mut i32) (i32.const 0))
  (global $thread_5_waiting (mut f64) (f64.const 0))
  (global $thread_5_active (mut i32) (i32.const 0))
  (global $thread_5_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_5_resumeDepth (mut i32) (i32.const 0))
  (global $thread_6_pc (mut i32) (i32.const 0))
  (global $thread_6_waiting (mut f64) (f64.const 0))
  (global $thread_6_active (mut i32) (i32.const 0))
  (global $thread_6_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_6_resumeDepth (mut i32) (i32.const 0))
  (global $thread_7_pc (mut i32) (i32.const 0))
  (global $thread_7_waiting (mut f64) (f64.const 0))
  (global $thread_7_active (mut i32) (i32.const 0))
  (global $thread_7_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_7_resumeDepth (mut i32) (i32.const 0))
  (global $thread_8_pc (mut i32) (i32.const 0))
  (global $thread_8_waiting (mut f64) (f64.const 0))
  (global $thread_8_active (mut i32) (i32.const 0))
  (global $thread_8_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_8_resumeDepth (mut i32) (i32.const 0))
  (global $thread_9_pc (mut i32) (i32.const 0))
  (global $thread_9_waiting (mut f64) (f64.const 0))
  (global $thread_9_active (mut i32) (i32.const 0))
  (global $thread_9_loopCounter_0 (mut i32) (i32.const -1))
  (global $thread_9_resumeDepth (mut i32) (i32.const 0))


  ;; ===== ENTITY ACCESSOR FUNCTIONS =====
  
  ;; Get entity base offset: 1024 + entityIndex * 72
  (func $getEntityOffset (param $idx i32) (result i32)
    (i32.add
      (i32.const 1024)
      (i32.mul (local.get $idx) (i32.const 120))))
  
  ;; Entity property getters/setters
  ;; X position (offset 0)
  (func $getX (param $idx i32) (result f64)
    (f64.load (call $getEntityOffset (local.get $idx))))
  
  (func $setX (param $idx i32) (param $val f64)
    (f64.store (call $getEntityOffset (local.get $idx)) (local.get $val)))
  
  ;; Y position (offset 8)
  (func $getY (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 8))))
  
  (func $setY (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 8)) (local.get $val)))
  
  ;; Rotation (offset 16)
  (func $getRotation (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 16))))
  
  (func $setRotation (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 16)) (local.get $val)))
  
  ;; Direction (offset 24)
  (func $getDirection (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 24))))
  
  (func $setDirection (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 24)) (local.get $val)))
  
  ;; ScaleX (offset 32)
  (func $getScaleX (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 32))))
  
  (func $setScaleX (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 32)) (local.get $val)))
  
  ;; ScaleY (offset 40)
  (func $getScaleY (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 40))))
  
  (func $setScaleY (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 40)) (local.get $val)))
  
  ;; Size (offset 48) - unified scale
  (func $getSize (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 48))))
  
  (func $setSize (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 48)) (local.get $val)))
  
  ;; Visible (offset 56, i32)
  (func $getVisible (param $idx i32) (result i32)
    (i32.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 56))))
  
  (func $setVisible (param $idx i32) (param $val i32)
    (i32.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 56)) (local.get $val)))
  
  ;; Picture index (offset 60, i32)
  (func $getPictureIndex (param $idx i32) (result i32)
    (i32.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 60))))
  
  (func $setPictureIndex (param $idx i32) (param $val i32)
    (i32.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 60)) (local.get $val)))
  
  ;; Scene index (offset 64, i32) - which scene this entity belongs to
  (func $getSceneIndex (param $idx i32) (result i32)
    (i32.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 64))))
  
  (func $setSceneIndex (param $idx i32) (param $val i32)
    (i32.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 64)) (local.get $val)))
  
  ;; ===== BRUSH COLOR STATE (stored in entity memory) =====
  ;; BrushColorR (offset 68, f64)
  (func $getBrushColorR (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 68))))
  (func $setBrushColorR (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 68)) (local.get $val)))
  
  ;; BrushColorG (offset 76, f64)
  (func $getBrushColorG (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 76))))
  (func $setBrushColorG (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 76)) (local.get $val)))
  
  ;; BrushColorB (offset 84, f64)
  (func $getBrushColorB (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 84))))
  (func $setBrushColorB (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 84)) (local.get $val)))
  
  ;; FillColorR (offset 92, f64)
  (func $getFillColorR (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 92))))
  (func $setFillColorR (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 92)) (local.get $val)))
  
  ;; FillColorG (offset 100, f64)
  (func $getFillColorG (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 100))))
  (func $setFillColorG (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 100)) (local.get $val)))
  
  ;; FillColorB (offset 108, f64)
  (func $getFillColorB (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 108))))
  (func $setFillColorB (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 108)) (local.get $val)))
  
  ;; InitialVisible (offset 116, i32) - stores the original visible state from project JSON
  ;; This is used by $updateSceneVisibility to preserve hidden-at-start objects
  (func $getInitialVisible (param $idx i32) (result i32)
    (i32.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 116))))
  
  (func $setInitialVisible (param $idx i32) (param $val i32)
    (i32.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 116)) (local.get $val)))
  
  ;; Set brush color RGB (convenience function)
  (func $setBrushColorRGB (param $idx i32) (param $r f64) (param $g f64) (param $b f64)
    (call $setBrushColorR (local.get $idx) (local.get $r))
    (call $setBrushColorG (local.get $idx) (local.get $g))
    (call $setBrushColorB (local.get $idx) (local.get $b)))
  
  ;; Set fill color RGB (convenience function)
  (func $setFillColorRGB (param $idx i32) (param $r f64) (param $g f64) (param $b f64)
    (call $setFillColorR (local.get $idx) (local.get $r))
    (call $setFillColorG (local.get $idx) (local.get $g))
    (call $setFillColorB (local.get $idx) (local.get $b)))
  
  ;; Unpack packed color (R*65536 + G*256 + B) and set brush color
  ;; If packed is negative, it's a string pointer (negated) to a hex color string like "#RRGGBB"
  (func $unpackAndSetBrushColor (param $idx i32) (param $packed f64)
    (local $packedInt i32)
    (if (f64.lt (local.get $packed) (f64.const 0))
      (then
        (call $parseHexAndSetBrushColor (local.get $idx)
          (i32.trunc_f64_s (f64.neg (local.get $packed)))))
      (else
        (local.set $packedInt (i32.trunc_f64_s (local.get $packed)))
        (call $setBrushColorR (local.get $idx) 
          (f64.convert_i32_s (i32.and (i32.shr_u (local.get $packedInt) (i32.const 16)) (i32.const 255))))
        (call $setBrushColorG (local.get $idx)
          (f64.convert_i32_s (i32.and (i32.shr_u (local.get $packedInt) (i32.const 8)) (i32.const 255))))
        (call $setBrushColorB (local.get $idx)
          (f64.convert_i32_s (i32.and (local.get $packedInt) (i32.const 255)))))))
  
  ;; Unpack packed color and set fill color
  ;; If packed is negative, it's a string pointer (negated) to a hex color string like "#RRGGBB"
  (func $unpackAndSetFillColor (param $idx i32) (param $packed f64)
    (local $packedInt i32)
    (if (f64.lt (local.get $packed) (f64.const 0))
      (then
        (call $parseHexAndSetFillColor (local.get $idx)
          (i32.trunc_f64_s (f64.neg (local.get $packed)))))
      (else
        (local.set $packedInt (i32.trunc_f64_s (local.get $packed)))
        (call $setFillColorR (local.get $idx)
          (f64.convert_i32_s (i32.and (i32.shr_u (local.get $packedInt) (i32.const 16)) (i32.const 255))))
        (call $setFillColorG (local.get $idx)
          (f64.convert_i32_s (i32.and (i32.shr_u (local.get $packedInt) (i32.const 8)) (i32.const 255))))
        (call $setFillColorB (local.get $idx)
          (f64.convert_i32_s (i32.and (local.get $packedInt) (i32.const 255)))))))
  
  ;; Set random brush color (using WASM random)
  (func $setRandomBrushColorInternal (param $idx i32)
    (call $setBrushColorR (local.get $idx) (call $floor (f64.mul (call $random) (f64.const 256))))
    (call $setBrushColorG (local.get $idx) (call $floor (f64.mul (call $random) (f64.const 256))))
    (call $setBrushColorB (local.get $idx) (call $floor (f64.mul (call $random) (f64.const 256))))
    (call $setFillColorR (local.get $idx) (call $floor (f64.mul (call $random) (f64.const 256))))
    (call $setFillColorG (local.get $idx) (call $floor (f64.mul (call $random) (f64.const 256))))
    (call $setFillColorB (local.get $idx) (call $floor (f64.mul (call $random) (f64.const 256)))))
  
  ;; Helper: Move in direction
  (func $moveInDirection (param $idx i32) (param $distance f64)
    (local $angle f64)
    (local $rad f64)
    ;; angle = rotation + direction - 90
    (local.set $angle 
      (f64.sub
        (f64.add (call $getRotation (local.get $idx)) (call $getDirection (local.get $idx)))
        (f64.const 90)))
    ;; rad = angle * PI / 180
    (local.set $rad (f64.mul (local.get $angle) (f64.const 0.017453292519943295)))
    ;; x += distance * cos(rad)
    (call $setX (local.get $idx)
      (f64.add (call $getX (local.get $idx))
        (f64.mul (local.get $distance) (call $cos (local.get $rad)))))
    ;; y -= distance * sin(rad)
    (call $setY (local.get $idx)
      (f64.sub (call $getY (local.get $idx))
        (f64.mul (local.get $distance) (call $sin (local.get $rad))))))


  ;; ===== VARIABLE/LIST VISIBILITY FUNCTIONS =====
  (func $getVarVisible_0 (result i32) (global.get $var_visible_0))
  (func $setVarVisible_0 (param $v i32) (global.set $var_visible_0 (local.get $v)))
  (func $getVarVisible_1 (result i32) (global.get $var_visible_1))
  (func $setVarVisible_1 (param $v i32) (global.set $var_visible_1 (local.get $v)))
  (func $getVarVisible_2 (result i32) (global.get $var_visible_2))
  (func $setVarVisible_2 (param $v i32) (global.set $var_visible_2 (local.get $v)))
  (func $getListVisible_0 (result i32) (global.get $list_visible_0))
  (func $setListVisible_0 (param $v i32) (global.set $list_visible_0 (local.get $v)))
  
  ;; ===== DIALOG FUNCTIONS =====
  (func $getDialogType_0 (result i32) (global.get $dialog_type_0))
  (func $setDialogType_0 (param $v i32) (global.set $dialog_type_0 (local.get $v)))
  (func $getDialogTextPtr_0 (result i32) (global.get $dialog_text_ptr_0))
  (func $setDialogTextPtr_0 (param $v i32) (global.set $dialog_text_ptr_0 (local.get $v)))
  
  ;; Dynamic dialog type setter (for user functions)
  (func $setDialogTypeDyn (param $idx i32) (param $v i32)
    (if (i32.eq (local.get $idx) (i32.const 0))
      (then (call $setDialogType_0 (local.get $v)))))
  
  ;; Dynamic dialog text pointer setter (for user functions)
  (func $setDialogTextPtrDyn (param $idx i32) (param $v i32)
    (if (i32.eq (local.get $idx) (i32.const 0))
      (then (call $setDialogTextPtr_0 (local.get $v)))))


  ;; ===== BLOCK HELPER FUNCTIONS =====
  
  ;; Get mouse X from memory
  (func $getMouseX (result f64)
    (f64.load (i32.const 16)))
  
  ;; Get mouse Y from memory
  (func $getMouseY (result f64)
    (f64.load (i32.const 24)))
  
  ;; Check if mouse is clicked
  (func $isMouseClicked (result i32)
    (i32.load (i32.const 32)))
  
  ;; Check if key is pressed (keycode 0-511)
  (func $isKeyPressed (param $keycode i32) (result i32)
    (local $byteOffset i32)
    (local $bitOffset i32)
    (local.set $byteOffset (i32.add (i32.const 36) (i32.shr_u (local.get $keycode) (i32.const 3))))
    (local.set $bitOffset (i32.and (local.get $keycode) (i32.const 7)))
    (i32.and
      (i32.shr_u (i32.load8_u (local.get $byteOffset)) (local.get $bitOffset))
      (i32.const 1)))
  
  ;; Get variable value
  (func $getVariable (param $varOffset i32) (result f64)
    (f64.load (local.get $varOffset)))
  
  ;; Set variable value
  (func $setVariable (param $varOffset i32) (param $val f64)
    (f64.store (local.get $varOffset) (local.get $val)))
  
  ;; Random number between min and max
  (func $randomRange (param $min f64) (param $max f64) (result f64)
    (f64.add
      (local.get $min)
      (f64.mul
        (call $random)
        (f64.sub (local.get $max) (local.get $min)))))
  
  ;; Random integer between min and max (inclusive)
  (func $randomInt (param $min f64) (param $max f64) (result f64)
    (call $floor
      (f64.add
        (local.get $min)
        (f64.mul
          (call $random)
          (f64.add (f64.sub (local.get $max) (local.get $min)) (f64.const 1))))))
  
  ;; ===== SCENE FUNCTIONS =====
  
  ;; Get current scene index
  (func $getCurrentScene (result i32)
    (global.get $currentScene))
  
  ;; Get scene count
  (func $getSceneCount (result i32)
    (global.get $sceneCount))
  
  ;; Update visibility of all entities based on current scene
  ;; Respects initialVisible - objects that were hidden at project start stay hidden
  (func $updateSceneVisibility
    (local $i i32)
    (local $entityCount i32)
    (local.set $entityCount (i32.const 1))
    (local.set $i (i32.const 0))
    (block $break
      (loop $loop
        (br_if $break (i32.ge_u (local.get $i) (local.get $entityCount)))
        ;; Set visible = 1 if entity's sceneIndex == currentScene AND initialVisible == 1, else 0
        (call $setVisible (local.get $i)
          (i32.and
            (i32.eq (call $getSceneIndex (local.get $i)) (global.get $currentScene))
            (call $getInitialVisible (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop))))
  
  ;; Start a specific scene by index
  (func $startScene (param $sceneIdx i32)
    ;; Bounds check
    (if (i32.and
          (i32.ge_s (local.get $sceneIdx) (i32.const 0))
          (i32.lt_s (local.get $sceneIdx) (global.get $sceneCount)))
      (then
        ;; Only change if different scene
        (if (i32.ne (local.get $sceneIdx) (global.get $currentScene))
          (then
            (global.set $currentScene (local.get $sceneIdx))
            (global.set $sceneJustChanged (i32.const 1))
            (call $updateSceneVisibility))))))
  
  ;; Start neighbor scene (offset: 1 for next, -1 for prev)
  (func $startNeighborScene (param $offset i32)
    (local $newScene i32)
    (local.set $newScene (i32.add (global.get $currentScene) (local.get $offset)))
    ;; Bounds check
    (if (i32.and
          (i32.ge_s (local.get $newScene) (i32.const 0))
          (i32.lt_s (local.get $newScene) (global.get $sceneCount)))
      (then
        (global.set $currentScene (local.get $newScene))
        (global.set $sceneJustChanged (i32.const 1))
        (call $updateSceneVisibility))))
  
  ;; ===== COLLISION DETECTION FUNCTIONS =====
  
  ;; Check if entity touches any edge (simple bounds check)
  (func $isTouchingEdge (param $idx i32) (result i32)
    (local $x f64)
    (local $y f64)
    (local.set $x (call $getX (local.get $idx)))
    (local.set $y (call $getY (local.get $idx)))
    (i32.or
      (i32.or
        (f64.le (local.get $x) (f64.const -240))
        (f64.ge (local.get $x) (f64.const 240)))
      (i32.or
        (f64.le (local.get $y) (f64.const -135))
        (f64.ge (local.get $y) (f64.const 135)))))
  
  ;; Check if entity touches top edge
  (func $isTouchingEdgeTop (param $idx i32) (result i32)
    (f64.ge (call $getY (local.get $idx)) (f64.const 135)))
  
  ;; Check if entity touches bottom edge
  (func $isTouchingEdgeBottom (param $idx i32) (result i32)
    (f64.le (call $getY (local.get $idx)) (f64.const -135)))
  
  ;; Check if entity touches left edge
  (func $isTouchingEdgeLeft (param $idx i32) (result i32)
    (f64.le (call $getX (local.get $idx)) (f64.const -240)))
  
  ;; Check if entity touches right edge
  (func $isTouchingEdgeRight (param $idx i32) (result i32)
    (f64.ge (call $getX (local.get $idx)) (f64.const 240)))
  
  ;; Check if entity touches mouse position (distance-based)
  (func $isTouchingMouse (param $idx i32) (result i32)
    (local $dx f64)
    (local $dy f64)
    (local.set $dx (f64.sub (call $getX (local.get $idx)) (call $getMouseX)))
    (local.set $dy (f64.sub (call $getY (local.get $idx)) (call $getMouseY)))
    ;; Check if distance < 50 (simple approximation)
    (f64.lt
      (f64.add (f64.mul (local.get $dx) (local.get $dx)) (f64.mul (local.get $dy) (local.get $dy)))
      (f64.const 2500)))
  
  ;; Check if two entities touch each other (distance-based)
  (func $isTouchingObject (param $idx1 i32) (param $idx2 i32) (result i32)
    (local $dx f64)
    (local $dy f64)
    (local.set $dx (f64.sub (call $getX (local.get $idx1)) (call $getX (local.get $idx2))))
    (local.set $dy (f64.sub (call $getY (local.get $idx1)) (call $getY (local.get $idx2))))
    ;; Check if distance < 50 (simple approximation)
    (f64.lt
      (f64.add (f64.mul (local.get $dx) (local.get $dx)) (f64.mul (local.get $dy) (local.get $dy)))
      (f64.const 2500)))
  
  ;; Check if object is clicked (mouse pressed and touching object)
  (func $isObjectClicked (param $idx i32) (result i32)
    (i32.and
      (call $isMouseClicked)
      (call $isTouchingMouse (local.get $idx))))
  
  ;; Find which entity is under the mouse (for click events)
  ;; Returns entity index or -1 if no entity under mouse
  ;; Checks entities in order 0, 1, 2, ... (entity 0 is on top in EntryJS)
  (func $findClickedEntity (result i32)
    (local $i i32)
    (local $entityCount i32)
    (local.set $entityCount (i32.const 1))
    (local.set $i (i32.const 0))
    (block $found (result i32)
      (block $notfound
        (loop $loop
          (br_if $notfound (i32.ge_u (local.get $i) (local.get $entityCount)))
          ;; Check if entity is visible and in current scene and mouse is touching it
          (if (i32.and
                (i32.and
                  (call $getVisible (local.get $i))
                  (i32.eq (call $getSceneIndex (local.get $i)) (global.get $currentScene)))
                (call $isTouchingMouse (local.get $i)))
            (then (br $found (local.get $i))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $loop)))
      (i32.const -1)))  ;; Return -1 if no entity found
  
  ;; Update click tracking state at start of tick
  ;; Detects new clicks and sets clickedEntityIndex
  (func $updateClickState
    (local $mouseNow i32)
    (local.set $mouseNow (call $isMouseClicked))
    ;; Detect new click (mouse now pressed, was not pressed before)
    (if (i32.and (local.get $mouseNow) (i32.eqz (global.get $prevMouseClicked)))
      (then
        ;; New click - find which entity is clicked
        (global.set $clickedEntityIndex (call $findClickedEntity)))))
  
  ;; Finalize click state at end of tick
  (func $finalizeClickState
    (local $mouseNow i32)
    (local.set $mouseNow (call $isMouseClicked))
    ;; If mouse was released, clear clicked entity
    (if (i32.and (i32.eqz (local.get $mouseNow)) (global.get $prevMouseClicked))
      (then
        (global.set $clickedEntityIndex (i32.const -1))))
    ;; Update previous mouse state
    (global.set $prevMouseClicked (local.get $mouseNow)))
  
  ;; Note: Brush/drawing functions and dialog functions are imported from JS
  ;; See imports section above
  
  ;; ===== LIST HELPER FUNCTIONS =====
  
  ;; Get list metadata offset by list index
  ;; List metadata: [length(i32), capacity(i32), data_ptr(i32), reserved(12 bytes)]
  (func $list_get_meta_ptr (param $listIdx i32) (result i32)
    (i32.add
      (i32.const 1168)
      (i32.mul (local.get $listIdx) (i32.const 24))))
  
  ;; Get list length
  (func $list_length (param $listIdx i32) (result i32)
    (i32.load (call $list_get_meta_ptr (local.get $listIdx))))
  
  ;; Set list length
  (func $list_set_length (param $listIdx i32) (param $len i32)
    (i32.store (call $list_get_meta_ptr (local.get $listIdx)) (local.get $len)))
  
  ;; Get list capacity
  (func $list_capacity (param $listIdx i32) (result i32)
    (i32.load (i32.add (call $list_get_meta_ptr (local.get $listIdx)) (i32.const 4))))
  
  ;; Get list data pointer
  (func $list_data_ptr (param $listIdx i32) (result i32)
    (i32.load (i32.add (call $list_get_meta_ptr (local.get $listIdx)) (i32.const 8))))
  
  ;; Get element offset (0-based index) - each element is 16 bytes
  (func $list_element_offset (param $listIdx i32) (param $index i32) (result i32)
    (i32.add
      (call $list_data_ptr (local.get $listIdx))
      (i32.mul (local.get $index) (i32.const 16))))
  
  ;; Get element type at index (0=number, 1=string)
  (func $list_get_type (param $listIdx i32) (param $index i32) (result i32)
    (local $len i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (if (result i32) (i32.or (i32.lt_s (local.get $index) (i32.const 0)) (i32.ge_s (local.get $index) (local.get $len)))
      (then (i32.const 0))
      (else (i32.load (i32.add (call $list_element_offset (local.get $listIdx) (local.get $index)) (i32.const 8))))))
  
  ;; Get string pointer at index
  (func $list_get_str_ptr (param $listIdx i32) (param $index i32) (result i32)
    (local $len i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (if (result i32) (i32.or (i32.lt_s (local.get $index) (i32.const 0)) (i32.ge_s (local.get $index) (local.get $len)))
      (then (i32.const 0))
      (else (i32.load (i32.add (call $list_element_offset (local.get $listIdx) (local.get $index)) (i32.const 12))))))
  
  ;; Get value at index (0-based) - returns f64, converts string to number if needed
  (func $list_get (param $listIdx i32) (param $index i32) (result f64)
    (local $len i32)
    (local $offset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    ;; Bounds check
    (if (result f64) (i32.or
          (i32.lt_s (local.get $index) (i32.const 0))
          (i32.ge_s (local.get $index) (local.get $len)))
      (then (f64.const 0))
      (else
        (local.set $offset (call $list_element_offset (local.get $listIdx) (local.get $index)))
        ;; Check type: 0=number, 1=string
        (if (result f64) (i32.eqz (i32.load (i32.add (local.get $offset) (i32.const 8))))
          (then (f64.load (local.get $offset)))
          (else (call $str_to_f64 (i32.load (i32.add (local.get $offset) (i32.const 12)))))))))
  
  ;; Set numeric value at index (0-based)
  (func $list_set (param $listIdx i32) (param $index i32) (param $value f64)
    (local $len i32)
    (local $offset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    ;; Bounds check
    (if (i32.and
          (i32.ge_s (local.get $index) (i32.const 0))
          (i32.lt_s (local.get $index) (local.get $len)))
      (then
        (local.set $offset (call $list_element_offset (local.get $listIdx) (local.get $index)))
        (f64.store (local.get $offset) (local.get $value))
        (i32.store (i32.add (local.get $offset) (i32.const 8)) (i32.const 0))  ;; type = number
        (i32.store (i32.add (local.get $offset) (i32.const 12)) (i32.const 0)))))  ;; str_ptr = 0
  
  ;; Set string value at index (0-based)
  (func $list_set_str (param $listIdx i32) (param $index i32) (param $strPtr i32)
    (local $len i32)
    (local $offset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    ;; Bounds check
    (if (i32.and
          (i32.ge_s (local.get $index) (i32.const 0))
          (i32.lt_s (local.get $index) (local.get $len)))
      (then
        (local.set $offset (call $list_element_offset (local.get $listIdx) (local.get $index)))
        (f64.store (local.get $offset) (f64.const 0))  ;; value = 0
        (i32.store (i32.add (local.get $offset) (i32.const 8)) (i32.const 1))  ;; type = string
        (i32.store (i32.add (local.get $offset) (i32.const 12)) (local.get $strPtr)))))
  
  ;; Push numeric value to end of list
  (func $list_push (param $listIdx i32) (param $value f64)
    (local $len i32)
    (local $cap i32)
    (local $offset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (local.set $cap (call $list_capacity (local.get $listIdx)))
    ;; Check capacity
    (if (i32.lt_s (local.get $len) (local.get $cap))
      (then
        (local.set $offset (call $list_element_offset (local.get $listIdx) (local.get $len)))
        ;; Store value at end (16-byte element: f64 value + i32 type + i32 str_ptr)
        (f64.store (local.get $offset) (local.get $value))
        (i32.store (i32.add (local.get $offset) (i32.const 8)) (i32.const 0))  ;; type = 0 (number)
        (i32.store (i32.add (local.get $offset) (i32.const 12)) (i32.const 0)) ;; str_ptr = 0
        ;; Increment length
        (call $list_set_length (local.get $listIdx) (i32.add (local.get $len) (i32.const 1))))))
  
  ;; Push string value to end of list
  (func $list_push_str (param $listIdx i32) (param $strPtr i32)
    (local $len i32)
    (local $cap i32)
    (local $offset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (local.set $cap (call $list_capacity (local.get $listIdx)))
    ;; Check capacity
    (if (i32.lt_s (local.get $len) (local.get $cap))
      (then
        (local.set $offset (call $list_element_offset (local.get $listIdx) (local.get $len)))
        ;; Store string at end (16-byte element)
        (f64.store (local.get $offset) (f64.const 0))  ;; value = 0 (unused for strings)
        (i32.store (i32.add (local.get $offset) (i32.const 8)) (i32.const 1))  ;; type = 1 (string)
        (i32.store (i32.add (local.get $offset) (i32.const 12)) (local.get $strPtr)) ;; str_ptr
        ;; Increment length
        (call $list_set_length (local.get $listIdx) (i32.add (local.get $len) (i32.const 1))))))
  
  ;; Insert numeric value at index (0-based), shift elements right
  (func $list_insert (param $listIdx i32) (param $index i32) (param $value f64)
    (local $len i32)
    (local $cap i32)
    (local $i i32)
    (local $srcOffset i32)
    (local $dstOffset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (local.set $cap (call $list_capacity (local.get $listIdx)))
    ;; Clamp index to valid range [0, len]
    (if (i32.lt_s (local.get $index) (i32.const 0))
      (then (local.set $index (i32.const 0))))
    (if (i32.gt_s (local.get $index) (local.get $len))
      (then (local.set $index (local.get $len))))
    ;; Check capacity
    (if (i32.lt_s (local.get $len) (local.get $cap))
      (then
        ;; Shift elements right from end to index (copy all 16 bytes per element)
        (local.set $i (local.get $len))
        (block $break
          (loop $shift
            (br_if $break (i32.le_s (local.get $i) (local.get $index)))
            (local.set $dstOffset (call $list_element_offset (local.get $listIdx) (local.get $i)))
            (local.set $srcOffset (call $list_element_offset (local.get $listIdx) (i32.sub (local.get $i) (i32.const 1))))
            ;; Copy all 16 bytes: value (8) + type (4) + str_ptr (4)
            (f64.store (local.get $dstOffset) (f64.load (local.get $srcOffset)))
            (i32.store (i32.add (local.get $dstOffset) (i32.const 8)) (i32.load (i32.add (local.get $srcOffset) (i32.const 8))))
            (i32.store (i32.add (local.get $dstOffset) (i32.const 12)) (i32.load (i32.add (local.get $srcOffset) (i32.const 12))))
            (local.set $i (i32.sub (local.get $i) (i32.const 1)))
            (br $shift)))
        ;; Store new numeric value with type tag
        (local.set $dstOffset (call $list_element_offset (local.get $listIdx) (local.get $index)))
        (f64.store (local.get $dstOffset) (local.get $value))
        (i32.store (i32.add (local.get $dstOffset) (i32.const 8)) (i32.const 0))  ;; type = 0 (number)
        (i32.store (i32.add (local.get $dstOffset) (i32.const 12)) (i32.const 0)) ;; str_ptr = 0
        ;; Increment length
        (call $list_set_length (local.get $listIdx) (i32.add (local.get $len) (i32.const 1))))))
  
  ;; Insert string value at index (0-based), shift elements right
  (func $list_insert_str (param $listIdx i32) (param $index i32) (param $strPtr i32)
    (local $len i32)
    (local $cap i32)
    (local $i i32)
    (local $srcOffset i32)
    (local $dstOffset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (local.set $cap (call $list_capacity (local.get $listIdx)))
    ;; Clamp index to valid range [0, len]
    (if (i32.lt_s (local.get $index) (i32.const 0))
      (then (local.set $index (i32.const 0))))
    (if (i32.gt_s (local.get $index) (local.get $len))
      (then (local.set $index (local.get $len))))
    ;; Check capacity
    (if (i32.lt_s (local.get $len) (local.get $cap))
      (then
        ;; Shift elements right from end to index (copy all 16 bytes per element)
        (local.set $i (local.get $len))
        (block $break
          (loop $shift
            (br_if $break (i32.le_s (local.get $i) (local.get $index)))
            (local.set $dstOffset (call $list_element_offset (local.get $listIdx) (local.get $i)))
            (local.set $srcOffset (call $list_element_offset (local.get $listIdx) (i32.sub (local.get $i) (i32.const 1))))
            ;; Copy all 16 bytes: value (8) + type (4) + str_ptr (4)
            (f64.store (local.get $dstOffset) (f64.load (local.get $srcOffset)))
            (i32.store (i32.add (local.get $dstOffset) (i32.const 8)) (i32.load (i32.add (local.get $srcOffset) (i32.const 8))))
            (i32.store (i32.add (local.get $dstOffset) (i32.const 12)) (i32.load (i32.add (local.get $srcOffset) (i32.const 12))))
            (local.set $i (i32.sub (local.get $i) (i32.const 1)))
            (br $shift)))
        ;; Store new string value with type tag
        (local.set $dstOffset (call $list_element_offset (local.get $listIdx) (local.get $index)))
        (f64.store (local.get $dstOffset) (f64.const 0))  ;; value = 0 (unused for strings)
        (i32.store (i32.add (local.get $dstOffset) (i32.const 8)) (i32.const 1))  ;; type = 1 (string)
        (i32.store (i32.add (local.get $dstOffset) (i32.const 12)) (local.get $strPtr)) ;; str_ptr
        ;; Increment length
        (call $list_set_length (local.get $listIdx) (i32.add (local.get $len) (i32.const 1))))))
  
  ;; Remove value at index (0-based), shift elements left
  (func $list_remove (param $listIdx i32) (param $index i32)
    (local $len i32)
    (local $i i32)
    (local $srcOffset i32)
    (local $dstOffset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    ;; Bounds check
    (if (i32.and
          (i32.ge_s (local.get $index) (i32.const 0))
          (i32.lt_s (local.get $index) (local.get $len)))
      (then
        ;; Shift elements left (copy all 16 bytes per element)
        (local.set $i (local.get $index))
        (block $break
          (loop $shift
            (br_if $break (i32.ge_s (local.get $i) (i32.sub (local.get $len) (i32.const 1))))
            (local.set $dstOffset (call $list_element_offset (local.get $listIdx) (local.get $i)))
            (local.set $srcOffset (call $list_element_offset (local.get $listIdx) (i32.add (local.get $i) (i32.const 1))))
            ;; Copy all 16 bytes: value (8) + type (4) + str_ptr (4)
            (f64.store (local.get $dstOffset) (f64.load (local.get $srcOffset)))
            (i32.store (i32.add (local.get $dstOffset) (i32.const 8)) (i32.load (i32.add (local.get $srcOffset) (i32.const 8))))
            (i32.store (i32.add (local.get $dstOffset) (i32.const 12)) (i32.load (i32.add (local.get $srcOffset) (i32.const 12))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $shift)))
        ;; Decrement length
        (call $list_set_length (local.get $listIdx) (i32.sub (local.get $len) (i32.const 1))))))
  
  ;; Check if list contains numeric value (returns 1 if found, 0 otherwise)
  ;; Only checks elements with type=0 (number)
  (func $list_contains (param $listIdx i32) (param $value f64) (result i32)
    (local $len i32)
    (local $i i32)
    (local $offset i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (local.set $i (i32.const 0))
    (block $found
      (block $not_found
        (loop $search
          (br_if $not_found (i32.ge_s (local.get $i) (local.get $len)))
          (local.set $offset (call $list_element_offset (local.get $listIdx) (local.get $i)))
          ;; Only compare if type=0 (number)
          (if (i32.eqz (i32.load (i32.add (local.get $offset) (i32.const 8))))
            (then
              (br_if $found (f64.eq (f64.load (local.get $offset)) (local.get $value)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $search)))
      (return (i32.const 0)))
    (i32.const 1))
  
  ;; Check if list contains string value (returns 1 if found, 0 otherwise)
  ;; Compares string contents, not pointers
  (func $list_contains_str (param $listIdx i32) (param $strPtr i32) (result i32)
    (local $len i32)
    (local $i i32)
    (local $offset i32)
    (local $elemStrPtr i32)
    (local $strLen i32)
    (local $elemStrLen i32)
    (local $j i32)
    (local $match i32)
    (local.set $len (call $list_length (local.get $listIdx)))
    (local.set $strLen (call $str_length (local.get $strPtr)))
    (local.set $i (i32.const 0))
    (block $found
      (block $not_found
        (loop $search
          (br_if $not_found (i32.ge_s (local.get $i) (local.get $len)))
          (local.set $offset (call $list_element_offset (local.get $listIdx) (local.get $i)))
          ;; Only compare if type=1 (string)
          (if (i32.eq (i32.load (i32.add (local.get $offset) (i32.const 8))) (i32.const 1))
            (then
              (local.set $elemStrPtr (i32.load (i32.add (local.get $offset) (i32.const 12))))
              (local.set $elemStrLen (call $str_length (local.get $elemStrPtr)))
              ;; Check if lengths match
              (if (i32.eq (local.get $strLen) (local.get $elemStrLen))
                (then
                  ;; Compare byte by byte
                  (local.set $match (i32.const 1))
                  (local.set $j (i32.const 0))
                  (block $nomatch
                    (loop $compare
                      (br_if $nomatch (i32.ge_s (local.get $j) (local.get $strLen)))
                      (if (i32.ne
                            (i32.load8_u (i32.add (i32.add (local.get $strPtr) (i32.const 4)) (local.get $j)))
                            (i32.load8_u (i32.add (i32.add (local.get $elemStrPtr) (i32.const 4)) (local.get $j))))
                        (then
                          (local.set $match (i32.const 0))
                          (br $nomatch)))
                      (local.set $j (i32.add (local.get $j) (i32.const 1)))
                      (br $compare)))
                  (br_if $found (local.get $match))))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $search)))
      (return (i32.const 0)))
    (i32.const 1))
  
  ;; Clear list (set length to 0)
  (func $list_clear (param $listIdx i32)
    (call $list_set_length (local.get $listIdx) (i32.const 0)))
  
  ;; ===== STRING HELPER FUNCTIONS =====
  
  ;; Allocate string in string pool (bump allocator)
  ;; Returns pointer to string (layout: [len:i32][data:bytes][null])
  (func $str_alloc (param $len i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $str_pool_ptr))
    ;; Store length at ptr
    (i32.store (local.get $ptr) (local.get $len))
    ;; Advance pool pointer: ptr + 4 (len) + len + 1 (null) + padding to 4-byte align
    (global.set $str_pool_ptr
      (i32.and
        (i32.add (i32.add (local.get $ptr) (i32.add (local.get $len) (i32.const 5))) (i32.const 3))
        (i32.const -4)))
    (local.get $ptr))
  
  ;; Get string length
  (func $str_length (param $ptr i32) (result i32)
    (if (result i32) (i32.eqz (local.get $ptr))
      (then (i32.const 0))
      (else (i32.load (local.get $ptr)))))
  
  ;; Get character at index (1-based) as char code
  (func $str_char_at (param $ptr i32) (param $idx i32) (result i32)
    (local $len i32)
    (local $zeroIdx i32)
    (if (result i32) (i32.eqz (local.get $ptr))
      (then (i32.const 0))
      (else
        (local.set $len (i32.load (local.get $ptr)))
        (local.set $zeroIdx (i32.sub (local.get $idx) (i32.const 1)))
        (if (result i32) (i32.or (i32.lt_s (local.get $zeroIdx) (i32.const 0)) (i32.ge_s (local.get $zeroIdx) (local.get $len)))
          (then (i32.const 0))
          (else (i32.load8_u (i32.add (i32.add (local.get $ptr) (i32.const 4)) (local.get $zeroIdx))))))))
  
  ;; Get character at index (1-based) as new string pointer
  (func $str_char_at_str (param $ptr i32) (param $idx i32) (result i32)
    (local $charCode i32)
    (local $newPtr i32)
    (local.set $charCode (call $str_char_at (local.get $ptr) (local.get $idx)))
    (if (result i32) (i32.eqz (local.get $charCode))
      (then (call $str_alloc (i32.const 0)))
      (else
        (local.set $newPtr (call $str_alloc (i32.const 1)))
        (i32.store8 (i32.add (local.get $newPtr) (i32.const 4)) (local.get $charCode))
        (i32.store8 (i32.add (local.get $newPtr) (i32.const 5)) (i32.const 0))
        (local.get $newPtr))))
  
  ;; Concatenate two strings
  (func $str_concat (param $ptr1 i32) (param $ptr2 i32) (result i32)
    (local $len1 i32)
    (local $len2 i32)
    (local $newPtr i32)
    (local $i i32)
    (local.set $len1 (if (result i32) (i32.eqz (local.get $ptr1)) (then (i32.const 0)) (else (i32.load (local.get $ptr1)))))
    (local.set $len2 (if (result i32) (i32.eqz (local.get $ptr2)) (then (i32.const 0)) (else (i32.load (local.get $ptr2)))))
    (local.set $newPtr (call $str_alloc (i32.add (local.get $len1) (local.get $len2))))
    ;; Copy first string
    (local.set $i (i32.const 0))
    (block $break1
      (loop $copy1
        (br_if $break1 (i32.ge_s (local.get $i) (local.get $len1)))
        (i32.store8
          (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $i))
          (i32.load8_u (i32.add (i32.add (local.get $ptr1) (i32.const 4)) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $copy1)))
    ;; Copy second string
    (local.set $i (i32.const 0))
    (block $break2
      (loop $copy2
        (br_if $break2 (i32.ge_s (local.get $i) (local.get $len2)))
        (i32.store8
          (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (i32.add (local.get $len1) (local.get $i)))
          (i32.load8_u (i32.add (i32.add (local.get $ptr2) (i32.const 4)) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $copy2)))
    ;; Null terminate
    (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (i32.add (local.get $len1) (local.get $len2))) (i32.const 0))
    (local.get $newPtr))
  
  ;; Get substring (1-based start and end, inclusive)
  (func $str_substring (param $ptr i32) (param $start i32) (param $end i32) (result i32)
    (local $len i32)
    (local $startIdx i32)
    (local $endIdx i32)
    (local $subLen i32)
    (local $newPtr i32)
    (local $i i32)
    (if (result i32) (i32.eqz (local.get $ptr))
      (then (call $str_alloc (i32.const 0)))
      (else
        (local.set $len (i32.load (local.get $ptr)))
        (local.set $startIdx (i32.sub (local.get $start) (i32.const 1)))
        (local.set $endIdx (local.get $end))
        ;; Clamp indices
        (if (i32.lt_s (local.get $startIdx) (i32.const 0)) (then (local.set $startIdx (i32.const 0))))
        (if (i32.gt_s (local.get $endIdx) (local.get $len)) (then (local.set $endIdx (local.get $len))))
        (local.set $subLen (i32.sub (local.get $endIdx) (local.get $startIdx)))
        (if (i32.lt_s (local.get $subLen) (i32.const 0)) (then (local.set $subLen (i32.const 0))))
        (local.set $newPtr (call $str_alloc (local.get $subLen)))
        ;; Copy substring
        (local.set $i (i32.const 0))
        (block $break
          (loop $copy
            (br_if $break (i32.ge_s (local.get $i) (local.get $subLen)))
            (i32.store8
              (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $i))
              (i32.load8_u (i32.add (i32.add (local.get $ptr) (i32.const 4)) (i32.add (local.get $startIdx) (local.get $i)))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $copy)))
        (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $subLen)) (i32.const 0))
        (local.get $newPtr))))
  
  ;; Find index of substring (returns 1-based index, 0 if not found)
  (func $str_index_of (param $str i32) (param $search i32) (result i32)
    (local $strLen i32)
    (local $searchLen i32)
    (local $i i32)
    (local $j i32)
    (local $match i32)
    (if (result i32) (i32.or (i32.eqz (local.get $str)) (i32.eqz (local.get $search)))
      (then (i32.const 0))
      (else
        (local.set $strLen (i32.load (local.get $str)))
        (local.set $searchLen (i32.load (local.get $search)))
        (if (result i32) (i32.gt_s (local.get $searchLen) (local.get $strLen))
          (then (i32.const 0))
          (else
            (local.set $i (i32.const 0))
            (block $found (result i32)
              (block $notfound
                (loop $outer
                  (br_if $notfound (i32.gt_s (local.get $i) (i32.sub (local.get $strLen) (local.get $searchLen))))
                  (local.set $match (i32.const 1))
                  (local.set $j (i32.const 0))
                  (block $nomatch
                    (loop $inner
                      (br_if $nomatch (i32.ge_s (local.get $j) (local.get $searchLen)))
                      (if (i32.ne
                            (i32.load8_u (i32.add (i32.add (local.get $str) (i32.const 4)) (i32.add (local.get $i) (local.get $j))))
                            (i32.load8_u (i32.add (i32.add (local.get $search) (i32.const 4)) (local.get $j))))
                        (then
                          (local.set $match (i32.const 0))
                          (br $nomatch)))
                      (local.set $j (i32.add (local.get $j) (i32.const 1)))
                      (br $inner)))
                  (if (local.get $match)
                    (then (br $found (i32.add (local.get $i) (i32.const 1)))))
                  (local.set $i (i32.add (local.get $i) (i32.const 1)))
                  (br $outer)))
              (i32.const 0)))))))
  
  ;; Replace first occurrence of old with new
  (func $str_replace (param $str i32) (param $old i32) (param $new i32) (result i32)
    (local $idx i32)
    (local $strLen i32)
    (local $oldLen i32)
    (local $newLen i32)
    (local $resultLen i32)
    (local $newPtr i32)
    (local $i i32)
    (local $srcIdx i32)
    (local.set $idx (call $str_index_of (local.get $str) (local.get $old)))
    (if (result i32) (i32.eqz (local.get $idx))
      (then
        ;; Not found, return copy of original
        (local.set $strLen (if (result i32) (i32.eqz (local.get $str)) (then (i32.const 0)) (else (i32.load (local.get $str)))))
        (local.set $newPtr (call $str_alloc (local.get $strLen)))
        (local.set $i (i32.const 0))
        (block $break
          (loop $copy
            (br_if $break (i32.ge_s (local.get $i) (local.get $strLen)))
            (i32.store8
              (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $i))
              (i32.load8_u (i32.add (i32.add (local.get $str) (i32.const 4)) (local.get $i))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $copy)))
        (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $strLen)) (i32.const 0))
        (local.get $newPtr))
      (else
        ;; Found, build replaced string
        (local.set $strLen (i32.load (local.get $str)))
        (local.set $oldLen (i32.load (local.get $old)))
        (local.set $newLen (if (result i32) (i32.eqz (local.get $new)) (then (i32.const 0)) (else (i32.load (local.get $new)))))
        (local.set $resultLen (i32.add (i32.sub (local.get $strLen) (local.get $oldLen)) (local.get $newLen)))
        (local.set $newPtr (call $str_alloc (local.get $resultLen)))
        (local.set $srcIdx (i32.sub (local.get $idx) (i32.const 1)))
        ;; Copy before
        (local.set $i (i32.const 0))
        (block $break1
          (loop $copy1
            (br_if $break1 (i32.ge_s (local.get $i) (local.get $srcIdx)))
            (i32.store8
              (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $i))
              (i32.load8_u (i32.add (i32.add (local.get $str) (i32.const 4)) (local.get $i))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $copy1)))
        ;; Copy new
        (local.set $i (i32.const 0))
        (block $break2
          (loop $copy2
            (br_if $break2 (i32.ge_s (local.get $i) (local.get $newLen)))
            (i32.store8
              (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (i32.add (local.get $srcIdx) (local.get $i)))
              (i32.load8_u (i32.add (i32.add (local.get $new) (i32.const 4)) (local.get $i))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $copy2)))
        ;; Copy after
        (local.set $i (i32.const 0))
        (block $break3
          (loop $copy3
            (br_if $break3 (i32.ge_s (local.get $i) (i32.sub (local.get $strLen) (i32.add (local.get $srcIdx) (local.get $oldLen)))))
            (i32.store8
              (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (i32.add (i32.add (local.get $srcIdx) (local.get $newLen)) (local.get $i)))
              (i32.load8_u (i32.add (i32.add (local.get $str) (i32.const 4)) (i32.add (i32.add (local.get $srcIdx) (local.get $oldLen)) (local.get $i)))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $copy3)))
        (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $resultLen)) (i32.const 0))
        (local.get $newPtr))))
  
  ;; Convert string to uppercase
  (func $str_to_upper (param $ptr i32) (result i32)
    (local $len i32)
    (local $newPtr i32)
    (local $i i32)
    (local $c i32)
    (if (result i32) (i32.eqz (local.get $ptr))
      (then (call $str_alloc (i32.const 0)))
      (else
        (local.set $len (i32.load (local.get $ptr)))
        (local.set $newPtr (call $str_alloc (local.get $len)))
        (local.set $i (i32.const 0))
        (block $break
          (loop $copy
            (br_if $break (i32.ge_s (local.get $i) (local.get $len)))
            (local.set $c (i32.load8_u (i32.add (i32.add (local.get $ptr) (i32.const 4)) (local.get $i))))
            ;; Convert a-z (97-122) to A-Z (65-90)
            (if (i32.and (i32.ge_u (local.get $c) (i32.const 97)) (i32.le_u (local.get $c) (i32.const 122)))
              (then (local.set $c (i32.sub (local.get $c) (i32.const 32)))))
            (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $i)) (local.get $c))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $copy)))
        (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $len)) (i32.const 0))
        (local.get $newPtr))))
  
  ;; Convert string to lowercase
  (func $str_to_lower (param $ptr i32) (result i32)
    (local $len i32)
    (local $newPtr i32)
    (local $i i32)
    (local $c i32)
    (if (result i32) (i32.eqz (local.get $ptr))
      (then (call $str_alloc (i32.const 0)))
      (else
        (local.set $len (i32.load (local.get $ptr)))
        (local.set $newPtr (call $str_alloc (local.get $len)))
        (local.set $i (i32.const 0))
        (block $break
          (loop $copy
            (br_if $break (i32.ge_s (local.get $i) (local.get $len)))
            (local.set $c (i32.load8_u (i32.add (i32.add (local.get $ptr) (i32.const 4)) (local.get $i))))
            ;; Convert A-Z (65-90) to a-z (97-122)
            (if (i32.and (i32.ge_u (local.get $c) (i32.const 65)) (i32.le_u (local.get $c) (i32.const 90)))
              (then (local.set $c (i32.add (local.get $c) (i32.const 32)))))
            (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $i)) (local.get $c))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $copy)))
        (i32.store8 (i32.add (i32.add (local.get $newPtr) (i32.const 4)) (local.get $len)) (i32.const 0))
        (local.get $newPtr))))
  
  ;; Convert f64 to string (simple integer conversion for now)
  (func $f64_to_str (param $val f64) (result i32)
    (local $intVal i32)
    (local $isNeg i32)
    (local $ptr i32)
    (local $digits i32)
    (local $temp i32)
    (local $i i32)
    ;; Simple conversion - just handle integers for now
    (local.set $intVal (i32.trunc_f64_s (local.get $val)))
    (local.set $isNeg (i32.lt_s (local.get $intVal) (i32.const 0)))
    (if (local.get $isNeg) (then (local.set $intVal (i32.sub (i32.const 0) (local.get $intVal)))))
    ;; Count digits
    (local.set $digits (i32.const 1))
    (local.set $temp (local.get $intVal))
    (block $countDone
      (loop $count
        (local.set $temp (i32.div_u (local.get $temp) (i32.const 10)))
        (br_if $countDone (i32.eqz (local.get $temp)))
        (local.set $digits (i32.add (local.get $digits) (i32.const 1)))
        (br $count)))
    ;; Allocate string
    (local.set $ptr (call $str_alloc (i32.add (local.get $digits) (local.get $isNeg))))
    ;; Write digits in reverse
    (local.set $temp (local.get $intVal))
    (local.set $i (i32.sub (i32.add (local.get $digits) (local.get $isNeg)) (i32.const 1)))
    (block $writeDone
      (loop $write
        (i32.store8
          (i32.add (i32.add (local.get $ptr) (i32.const 4)) (local.get $i))
          (i32.add (i32.const 48) (i32.rem_u (local.get $temp) (i32.const 10))))
        (local.set $temp (i32.div_u (local.get $temp) (i32.const 10)))
        (local.set $i (i32.sub (local.get $i) (i32.const 1)))
        (br_if $writeDone (i32.lt_s (local.get $i) (local.get $isNeg)))
        (br $write)))
    ;; Write negative sign if needed
    (if (local.get $isNeg)
      (then (i32.store8 (i32.add (local.get $ptr) (i32.const 4)) (i32.const 45))))
    ;; Null terminate
    (i32.store8 (i32.add (i32.add (local.get $ptr) (i32.const 4)) (i32.add (local.get $digits) (local.get $isNeg))) (i32.const 0))
    (local.get $ptr))
  
  ;; Compare two strings for equality (returns i32: 1 if equal, 0 if not)
  (func $str_equals (param $ptr1 i32) (param $ptr2 i32) (result i32)
    (local $len1 i32)
    (local $len2 i32)
    (local $i i32)
    ;; Handle null pointers
    (if (i32.and (i32.eqz (local.get $ptr1)) (i32.eqz (local.get $ptr2)))
      (then (return (i32.const 1))))
    (if (i32.or (i32.eqz (local.get $ptr1)) (i32.eqz (local.get $ptr2)))
      (then (return (i32.const 0))))
    ;; Compare lengths first
    (local.set $len1 (i32.load (local.get $ptr1)))
    (local.set $len2 (i32.load (local.get $ptr2)))
    (if (i32.ne (local.get $len1) (local.get $len2))
      (then (return (i32.const 0))))
    ;; Compare byte by byte
    (local.set $i (i32.const 0))
    (block $not_equal
      (loop $compare
        (br_if $not_equal (i32.ge_s (local.get $i) (local.get $len1)))
        (if (i32.ne
              (i32.load8_u (i32.add (i32.add (local.get $ptr1) (i32.const 4)) (local.get $i)))
              (i32.load8_u (i32.add (i32.add (local.get $ptr2) (i32.const 4)) (local.get $i))))
          (then (return (i32.const 0))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $compare)))
    (i32.const 1))
  
  ;; Convert string to f64
  (func $str_to_f64 (param $ptr i32) (result f64)
    (local $len i32)
    (local $i i32)
    (local $c i32)
    (local $result f64)
    (local $isNeg i32)
    (if (result f64) (i32.eqz (local.get $ptr))
      (then (f64.const 0))
      (else
        (local.set $len (i32.load (local.get $ptr)))
        (local.set $result (f64.const 0))
        (local.set $i (i32.const 0))
        ;; Check for negative
        (if (i32.and (i32.gt_s (local.get $len) (i32.const 0))
                     (i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.const 4))) (i32.const 45)))
          (then
            (local.set $isNeg (i32.const 1))
            (local.set $i (i32.const 1))))
        ;; Parse digits
        (block $done
          (loop $parse
            (br_if $done (i32.ge_s (local.get $i) (local.get $len)))
            (local.set $c (i32.load8_u (i32.add (i32.add (local.get $ptr) (i32.const 4)) (local.get $i))))
            (br_if $done (i32.or (i32.lt_u (local.get $c) (i32.const 48)) (i32.gt_u (local.get $c) (i32.const 57))))
            (local.set $result
              (f64.add
                (f64.mul (local.get $result) (f64.const 10))
                (f64.convert_i32_u (i32.sub (local.get $c) (i32.const 48)))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $parse)))
        (if (result f64) (local.get $isNeg)
          (then (f64.neg (local.get $result)))
          (else (local.get $result))))))    ;; Get list value as string pointer (converts number to string if needed)
  (func $list_get_as_str (param $listIdx i32) (param $index i32) (result i32)
    ;; For now, just convert the numeric value to string
    ;; TODO: Support mixed-type lists with type tagging
    (call $f64_to_str (call $list_get (local.get $listIdx) (local.get $index))))
  
  ;; Convert f64 to string pointer, or dereference if it's a negative-encoded string pointer
  ;; Convention: negative f64 = negated string pointer (i32), positive f64 = numeric value
  (func $f64_to_str_or_deref (param $val f64) (result i32)
    (if (result i32) (f64.lt (local.get $val) (f64.const 0))
      (then (i32.trunc_f64_s (f64.neg (local.get $val))))
      (else (call $f64_to_str (local.get $val)))))
  
  ;; Convert a hex character ASCII code to its digit value (0-15)
  ;; '0'-'9' (48-57) -> 0-9, 'A'-'F' (65-70) -> 10-15, 'a'-'f' (97-102) -> 10-15
  (func $hexCharToDigit (param $c i32) (result i32)
    (if (result i32) (i32.and (i32.ge_u (local.get $c) (i32.const 48)) (i32.le_u (local.get $c) (i32.const 57)))
      (then (i32.sub (local.get $c) (i32.const 48)))
      (else
        (if (result i32) (i32.and (i32.ge_u (local.get $c) (i32.const 65)) (i32.le_u (local.get $c) (i32.const 70)))
          (then (i32.sub (local.get $c) (i32.const 55)))
          (else
            (if (result i32) (i32.and (i32.ge_u (local.get $c) (i32.const 97)) (i32.le_u (local.get $c) (i32.const 102)))
              (then (i32.sub (local.get $c) (i32.const 87)))
              (else (i32.const 0))))))))
  
  ;; Parse hex color string "#RRGGBB" or "RRGGBB" and set brush color
  ;; String layout: [len:i32 at ptr][data at ptr+4]
  (func $parseHexAndSetBrushColor (param $idx i32) (param $strPtr i32)
    (local $len i32)
    (local $r i32) (local $g i32) (local $b i32)
    (local $dataStart i32)
    (local.set $len (call $str_length (local.get $strPtr)))
    (if (i32.and
          (i32.ge_s (local.get $len) (i32.const 7))
          (i32.eq (i32.load8_u (i32.add (local.get $strPtr) (i32.const 4))) (i32.const 35)))
      (then
        (local.set $dataStart (i32.add (local.get $strPtr) (i32.const 5))))
      (else
        (if (i32.ge_s (local.get $len) (i32.const 6))
          (then
            (local.set $dataStart (i32.add (local.get $strPtr) (i32.const 4)))))))
    (if (local.get $dataStart)
      (then
        (local.set $r (i32.add
          (i32.mul (call $hexCharToDigit (i32.load8_u (local.get $dataStart))) (i32.const 16))
          (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 1))))))
        (local.set $g (i32.add
          (i32.mul (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 2)))) (i32.const 16))
          (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 3))))))
        (local.set $b (i32.add
          (i32.mul (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 4)))) (i32.const 16))
          (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 5))))))
        (call $setBrushColorRGB (local.get $idx)
          (f64.convert_i32_s (local.get $r))
          (f64.convert_i32_s (local.get $g))
          (f64.convert_i32_s (local.get $b))))))
  
  ;; Parse hex color string "#RRGGBB" or "RRGGBB" and set fill color
  (func $parseHexAndSetFillColor (param $idx i32) (param $strPtr i32)
    (local $len i32)
    (local $r i32) (local $g i32) (local $b i32)
    (local $dataStart i32)
    (local.set $len (call $str_length (local.get $strPtr)))
    (if (i32.and
          (i32.ge_s (local.get $len) (i32.const 7))
          (i32.eq (i32.load8_u (i32.add (local.get $strPtr) (i32.const 4))) (i32.const 35)))
      (then
        (local.set $dataStart (i32.add (local.get $strPtr) (i32.const 5))))
      (else
        (if (i32.ge_s (local.get $len) (i32.const 6))
          (then
            (local.set $dataStart (i32.add (local.get $strPtr) (i32.const 4)))))))
    (if (local.get $dataStart)
      (then
        (local.set $r (i32.add
          (i32.mul (call $hexCharToDigit (i32.load8_u (local.get $dataStart))) (i32.const 16))
          (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 1))))))
        (local.set $g (i32.add
          (i32.mul (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 2)))) (i32.const 16))
          (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 3))))))
        (local.set $b (i32.add
          (i32.mul (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 4)))) (i32.const 16))
          (call $hexCharToDigit (i32.load8_u (i32.add (local.get $dataStart) (i32.const 5))))))
        (call $setFillColorRGB (local.get $idx)
          (f64.convert_i32_s (local.get $r))
          (f64.convert_i32_s (local.get $g))
          (f64.convert_i32_s (local.get $b))))))


  ;; ===== MESSAGE/SIGNAL FUNCTIONS =====
  
  ;; Set message flag by index
  (func $setMessageFlag (param $msgIdx i32)
    (if (i32.eq (local.get $msgIdx) (i32.const 0))
      (then (global.set $msg_flag_0 (i32.const 1)))))
  
  ;; Clear all message flags (called at end of frame)
  (func $clearAllMessageFlags
    (global.set $msg_flag_0 (i32.const 0)))


  ;; ===== USER FUNCTIONS =====
  
  ;; User function: func_0
  (func $user_func_t98t (param $entityIdx i32) (param $param_0 f64) 
    (local $temp f64)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    (local $local_0 f64) ;; 지역변수
    (local $local_1 f64) ;; 지역변수1
    
          ;; set_func_variable
          (local.set $local_0 (local.get $param_0))
          ;; if_else
          (if (f64.ne (local.get $local_0) (f64.add (f64.convert_i32_s (call $list_length (i32.const 0))) (f64.const 1)))
            (then 
          ;; locate_xy
          (call $setX (local.get $entityIdx) (call $list_get (i32.const 0) (i32.trunc_f64_s (f64.sub (local.get $local_0) (f64.const 1)))))
          (call $setY (local.get $entityIdx) (call $list_get (i32.const 0) (i32.trunc_f64_s (f64.sub (local.get $local_0) (f64.const 1)))))
          (call $brushNotifyPosition (local.get $entityIdx) (call $getX (local.get $entityIdx)) (call $getY (local.get $entityIdx)))
          ;; dialog: speak (dynamic entity)
          (call $setDialogTextPtrDyn (local.get $entityIdx) (call $f64_to_str (local.get $local_0)))
          (call $setDialogTypeDyn (local.get $entityIdx) (i32.const 1))
          ;; set_func_variable
          (local.set $local_0 (f64.add (local.get $local_0) (f64.const 1)))
          ;; Call function: func_0
          (call $user_func_t98t (local.get $entityIdx) (local.get $local_0)))
            (else 
          ;; add_value_to_list: 리스트
          (call $list_push (i32.const 0) (f64.add (call $list_get (i32.const 0) (i32.trunc_f64_s (f64.sub (f64.convert_i32_s (call $list_length (i32.const 0))) (f64.const 1)))) (f64.const 1)))))
  )
  
  ;; User function: func_1
  (func $user_func_sa1w (param $entityIdx i32) (param $param_0 f64) 
    (local $temp f64)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    (local $local_0 f64) ;; 지역변수
    
          ;; set_func_variable
          (local.set $local_0 (local.get $param_0))
          ;; dialog: speak (dynamic entity)
          (call $setDialogTextPtrDyn (local.get $entityIdx) (call $f64_to_str (local.get $local_0)))
          (call $setDialogTypeDyn (local.get $entityIdx) (i32.const 1))
  )


  ;; ===== THREAD EXECUTION FUNCTIONS =====
  
  ;; Thread 0: when_run_button_click for entity 0
  (func $thread_0_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_0_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_0_waiting) (f64.const 0))
      (then
        (global.set $thread_0_waiting
          (f64.sub (global.get $thread_0_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        (block $pc_0
          (br_if $pc_0 (i32.ne (local.get $pc) (i32.const 0)))
          ;; dialog: speak
          (call $setDialogTextPtr_0 (block (result i32)
            (local.set $temp_str_ptr (call $str_alloc (i32.const 12)))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 0)) (i32.const 237))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 1)) (i32.const 129))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 2)) (i32.const 180))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 3)) (i32.const 235))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 4)) (i32.const 166))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 5)) (i32.const 173))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 6)) (i32.const 237))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 7)) (i32.const 149))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 8)) (i32.const 152))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 9)) (i32.const 234))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 10)) (i32.const 184))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 11)) (i32.const 176))
            (i32.store8 (i32.add (i32.add (local.get $temp_str_ptr) (i32.const 4)) (i32.const 12)) (i32.const 0))
            (local.get $temp_str_ptr)))
          (call $setDialogType_0 (i32.const 1))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_0_pc (local.get $pc))
          (global.set $thread_0_resumeDepth (i32.const 0))
          (br $done))
        ;; End of thread
        (global.set $thread_0_pc (i32.const 0))
        (global.set $thread_0_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 1: when_object_click for entity 0
  (func $thread_1_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_1_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_1_waiting) (f64.const 0))
      (then
        (global.set $thread_1_waiting
          (f64.sub (global.get $thread_1_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        (block $pc_0
          (br_if $pc_0 (i32.ne (local.get $pc) (i32.const 0)))
          ;; rotate_relative
          (call $setRotation (i32.const 0)
            (f64.add (call $getRotation (i32.const 0)) (f64.const 90)))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_1_pc (local.get $pc))
          (global.set $thread_1_resumeDepth (i32.const 0))
          (br $done))
        (block $pc_1
          (br_if $pc_1 (i32.ne (local.get $pc) (i32.const 1)))
          ;; message_cast (send signal: 신호)
          (call $setMessageFlag (i32.const 0))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_1_pc (local.get $pc))
          (global.set $thread_1_resumeDepth (i32.const 0))
          (br $done))
        ;; End of thread
        (global.set $thread_1_pc (i32.const 0))
        (global.set $thread_1_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 2: when_message_cast for entity 0
  (func $thread_2_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_2_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_2_waiting) (f64.const 0))
      (then
        (global.set $thread_2_waiting
          (f64.sub (global.get $thread_2_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        (block $pc_0
          (br_if $pc_0 (i32.ne (local.get $pc) (i32.const 0)))
          ;; Call function: func_0
          (call $user_func_t98t (i32.const 0) (f64.const 1))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_2_pc (local.get $pc))
          (global.set $thread_2_resumeDepth (i32.const 0))
          (br $done))
        ;; End of thread
        (global.set $thread_2_pc (i32.const 0))
        (global.set $thread_2_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 3: repeat_inf for entity 0
  (func $thread_3_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_3_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_3_waiting) (f64.const 0))
      (then
        (global.set $thread_3_waiting
          (f64.sub (global.get $thread_3_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        ;; End of thread
        (global.set $thread_3_pc (i32.const 0))
        (global.set $thread_3_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 4: func_sa1w for entity 0
  (func $thread_4_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_4_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_4_waiting) (f64.const 0))
      (then
        (global.set $thread_4_waiting
          (f64.sub (global.get $thread_4_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        ;; End of thread
        (global.set $thread_4_pc (i32.const 0))
        (global.set $thread_4_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 5: add_value_to_list for entity 0
  (func $thread_5_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_5_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_5_waiting) (f64.const 0))
      (then
        (global.set $thread_5_waiting
          (f64.sub (global.get $thread_5_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        ;; End of thread
        (global.set $thread_5_pc (i32.const 0))
        (global.set $thread_5_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 6: get_variable for entity 0
  (func $thread_6_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_6_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_6_waiting) (f64.const 0))
      (then
        (global.set $thread_6_waiting
          (f64.sub (global.get $thread_6_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        ;; End of thread
        (global.set $thread_6_pc (i32.const 0))
        (global.set $thread_6_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 7: set_variable for entity 0
  (func $thread_7_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_7_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_7_waiting) (f64.const 0))
      (then
        (global.set $thread_7_waiting
          (f64.sub (global.get $thread_7_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        ;; End of thread
        (global.set $thread_7_pc (i32.const 0))
        (global.set $thread_7_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 8: dialog for entity 0
  (func $thread_8_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_8_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_8_waiting) (f64.const 0))
      (then
        (global.set $thread_8_waiting
          (f64.sub (global.get $thread_8_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        ;; End of thread
        (global.set $thread_8_pc (i32.const 0))
        (global.set $thread_8_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )
  
  ;; Thread 9: remove_value_from_list for entity 0
  (func $thread_9_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    (local $temp_str_ptr i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_9_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_9_waiting) (f64.const 0))
      (then
        (global.set $thread_9_waiting
          (f64.sub (global.get $thread_9_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        ;; End of thread
        (global.set $thread_9_pc (i32.const 0))
        (global.set $thread_9_resumeDepth (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )


  ;; ===== MAIN LOOP =====
  
  ;; Initialize entities with their starting values
  (func $init
    ;; Reset scene to first scene
    (global.set $currentScene (i32.const 0))
    (global.set $sceneJustChanged (i32.const 0))
    ;; Reset click tracking state
    (global.set $prevMouseClicked (i32.const 0))
    (global.set $clickedEntityIndex (i32.const -1))
    
    ;; Initialize entity 0: 엔트리봇 (scene: 0)
    (call $setX (i32.const 0) (f64.const 0))
    (call $setY (i32.const 0) (f64.const 0))
    (call $setRotation (i32.const 0) (f64.const 0))
    (call $setDirection (i32.const 0) (f64.const 90))
    (call $setScaleX (i32.const 0) (f64.const 0.5128205128205128))
    (call $setScaleY (i32.const 0) (f64.const 0.5128205128205128))
    (call $setSize (i32.const 0) (f64.const 51.28205128205128))
    (call $setVisible (i32.const 0) (i32.const 1))
    (call $setInitialVisible (i32.const 0) (i32.const 1))
    (call $setPictureIndex (i32.const 0) (i32.const 0))
    (call $setSceneIndex (i32.const 0) (i32.const 0))
    ;; Initialize brush colors to default red (255, 0, 0)
    (call $setBrushColorRGB (i32.const 0) (f64.const 255) (f64.const 0) (f64.const 0))
    (call $setFillColorRGB (i32.const 0) (f64.const 255) (f64.const 0) (f64.const 0))
    
    ;; Initialize variable: 변수
    (call $setVariable (i32.const 1144) (f64.const 0))
    ;; Initialize variable: 초시계
    (call $setVariable (i32.const 1152) (f64.const 0))
    ;; Initialize variable: 대답
    (call $setVariable (i32.const 1160) (f64.const 0))
    
    ;; Initialize list: 리스트 (index 0)
    ;; Set metadata: length=0, capacity=1000000, data_ptr=1192
    (i32.store (i32.const 1168) (i32.const 0))
    (i32.store (i32.const 1172) (i32.const 1000000))
    (i32.store (i32.const 1176) (i32.const 1192))
    (call $list_push (i32.const 0) (f64.const 1))
    (call $list_push (i32.const 0) (f64.const 2))
    (call $list_push (i32.const 0) (f64.const 3))
    (call $list_push (i32.const 0) (f64.const 4))
    (call $list_push (i32.const 0) (f64.const 5))
    (call $list_push (i32.const 0) (f64.const 6))
    (call $list_push (i32.const 0) (f64.const 7))
    (call $list_push (i32.const 0) (f64.const 8))
    (call $list_push (i32.const 0) (f64.const 9))
    (call $list_push (i32.const 0) (f64.const 10))
    (global.set $running (i32.const 1)))
  
  ;; Main tick function - called every frame from JS
  (func $tick (param $dt f64)
    ;; Reset string pool to reclaim temporary strings from previous tick
    (global.set $str_pool_ptr (i32.const 16001192))
    (global.set $deltaTime (local.get $dt))
    
    ;; Update click tracking state (detect new clicks)
    (call $updateClickState)
    
    ;; Handle scene change events (when_scene_start)
    
    
    ;; Reset scene changed flag after processing
    (global.set $sceneJustChanged (i32.const 0))
    
    ;; Handle object click events (when_object_click)
    
    ;; Activate thread 1 when object 0 is clicked
    (if (i32.and
          ;; Check if this entity was just clicked
          (i32.eq (global.get $clickedEntityIndex) (i32.const 0))
          ;; And this is a new click (prev was not clicked)
          (i32.eqz (global.get $prevMouseClicked)))
      (then
        (global.set $thread_1_pc (i32.const 0))
        (global.set $thread_1_waiting (f64.const 0))
        (global.set $thread_1_loopCounter_0 (i32.const -1))
        (global.set $thread_1_resumeDepth (i32.const 0))
        (global.set $thread_1_active (i32.const 1))))
    
    ;; Handle object click canceled events (when_object_click_canceled)
    
    
    ;; Handle message events (when_message_cast)
    
    ;; Activate thread 2 when message "신호" is received (entity scene: 0)
    (if (i32.and
          (global.get $msg_flag_0)
          (i32.eq (i32.const 0) (global.get $currentScene)))
      (then
        (global.set $thread_2_pc (i32.const 0))
        (global.set $thread_2_waiting (f64.const 0))
        (global.set $thread_2_loopCounter_0 (i32.const -1))
        (global.set $thread_2_resumeDepth (i32.const 0))
        (global.set $thread_2_active (i32.const 1))))
    
    ;; Clear message flags AFTER handlers activated, BEFORE threads execute
    ;; This ensures signals sent in frame N are received in frame N+1
    (call $clearAllMessageFlags)
    
    ;; Check events and activate threads
    
    ;; Activate thread 0 on start (entity scene: 0)
    (if (i32.and
          (i32.eqz (global.get $frameCount))
          (i32.eq (i32.const 0) (global.get $currentScene)))
      (then
        (global.set $thread_0_loopCounter_0 (i32.const -1))
        (global.set $thread_0_resumeDepth (i32.const 0))
        (global.set $thread_0_active (i32.const 1))))
    
    ;; Execute active threads
    
    ;; Run thread 0
    (if (global.get $thread_0_active)
      (then
        (if (i32.eqz (call $thread_0_run (i32.const 0)))
          (then (global.set $thread_0_active (i32.const 0))))))
    ;; Run thread 1
    (if (global.get $thread_1_active)
      (then
        (if (i32.eqz (call $thread_1_run (i32.const 0)))
          (then (global.set $thread_1_active (i32.const 0))))))
    ;; Run thread 2
    (if (global.get $thread_2_active)
      (then
        (if (i32.eqz (call $thread_2_run (i32.const 0)))
          (then (global.set $thread_2_active (i32.const 0))))))
    ;; Run thread 3
    (if (global.get $thread_3_active)
      (then
        (if (i32.eqz (call $thread_3_run (i32.const 0)))
          (then (global.set $thread_3_active (i32.const 0))))))
    ;; Run thread 4
    (if (global.get $thread_4_active)
      (then
        (if (i32.eqz (call $thread_4_run (i32.const 0)))
          (then (global.set $thread_4_active (i32.const 0))))))
    ;; Run thread 5
    (if (global.get $thread_5_active)
      (then
        (if (i32.eqz (call $thread_5_run (i32.const 0)))
          (then (global.set $thread_5_active (i32.const 0))))))
    ;; Run thread 6
    (if (global.get $thread_6_active)
      (then
        (if (i32.eqz (call $thread_6_run (i32.const 0)))
          (then (global.set $thread_6_active (i32.const 0))))))
    ;; Run thread 7
    (if (global.get $thread_7_active)
      (then
        (if (i32.eqz (call $thread_7_run (i32.const 0)))
          (then (global.set $thread_7_active (i32.const 0))))))
    ;; Run thread 8
    (if (global.get $thread_8_active)
      (then
        (if (i32.eqz (call $thread_8_run (i32.const 0)))
          (then (global.set $thread_8_active (i32.const 0))))))
    ;; Run thread 9
    (if (global.get $thread_9_active)
      (then
        (if (i32.eqz (call $thread_9_run (i32.const 0)))
          (then (global.set $thread_9_active (i32.const 0))))))
    
    ;; Finalize click state (update prevMouseClicked, clear clickedEntityIndex on release)
    (call $finalizeClickState)
    
    ;; Increment frame counter
    (global.set $frameCount (i32.add (global.get $frameCount) (i32.const 1))))
  
  ;; Stop execution
  (func $stop
    (global.set $running (i32.const 0)))
  
  ;; Get entity count
  (func $getEntityCount (result i32)
    (i32.const 1))


  ;; ===== EXPORTS =====
  (export "init" (func $init))
  (export "tick" (func $tick))
  (export "stop" (func $stop))
  (export "getEntityCount" (func $getEntityCount))
  (export "getX" (func $getX))
  (export "getY" (func $getY))
  (export "getRotation" (func $getRotation))
  (export "getDirection" (func $getDirection))
  (export "getScaleX" (func $getScaleX))
  (export "getScaleY" (func $getScaleY))
  (export "getSize" (func $getSize))
  (export "getVisible" (func $getVisible))
  (export "getPictureIndex" (func $getPictureIndex))
  (export "getSceneIndex" (func $getSceneIndex))
  (export "getCurrentScene" (func $getCurrentScene))
  (export "getSceneCount" (func $getSceneCount))
  (export "startScene" (func $startScene))
  (export "startNeighborScene" (func $startNeighborScene))
  ;; Brush color exports (for JS renderer to read)
  (export "getBrushColorR" (func $getBrushColorR))
  (export "getBrushColorG" (func $getBrushColorG))
  (export "getBrushColorB" (func $getBrushColorB))
  (export "getFillColorR" (func $getFillColorR))
  (export "getFillColorG" (func $getFillColorG))
  (export "getFillColorB" (func $getFillColorB))
  (export "getVarVisible_0" (func $getVarVisible_0))
  (export "getVarVisible_1" (func $getVarVisible_1))
  (export "getVarVisible_2" (func $getVarVisible_2))
  (export "getListVisible_0" (func $getListVisible_0))
  (export "getDialogType_0" (func $getDialogType_0))
  (export "getDialogTextPtr_0" (func $getDialogTextPtr_0))
  (export "str_length" (func $str_length))
  (export "getVariable" (func $getVariable))
  (export "list_length" (func $list_length))
  (export "list_get" (func $list_get))
)