(module
  ;; EntryJS Compiled Project
  ;; Generated by EntryJS-to-WASM Compiler
  ;; 
  ;; Memory Layout:
  ;; - 0-63: System state (frame count, time, mouse, keys, etc.)
  ;; - 64-1023: Reserved
  ;; - 1024+: Entity data (64 bytes each)
  ;; - After entities: Variables (8 bytes each)


  ;; ===== IMPORTS =====
  ;; Math functions from JS
  (import "math" "sin" (func $sin (param f64) (result f64)))
  (import "math" "cos" (func $cos (param f64) (result f64)))
  (import "math" "sqrt" (func $sqrt (param f64) (result f64)))
  (import "math" "random" (func $random (result f64)))
  (import "math" "floor" (func $floor (param f64) (result f64)))
  (import "math" "ceil" (func $ceil (param f64) (result f64)))
  (import "math" "abs" (func $abs (param f64) (result f64)))
  (import "math" "atan2" (func $atan2 (param f64 f64) (result f64)))
  
  ;; System callbacks
  (import "system" "log" (func $log (param f64)))
  (import "system" "playSound" (func $playSound (param i32 i32)))
  (import "system" "sendMessage" (func $sendMessage (param i32)))
  
  ;; Brush/Drawing functions (implemented in JS renderer for performance)
  (import "brush" "startDrawing" (func $startDrawing (param i32)))
  (import "brush" "stopDrawing" (func $stopDrawing (param i32)))
  (import "brush" "stamp" (func $stamp (param i32)))
  (import "brush" "clearBrush" (func $clearBrush))
  (import "brush" "setBrushColor" (func $setBrushColor (param i32 i32 i32 i32)))
  (import "brush" "setRandomBrushColor" (func $setRandomBrushColor (param i32)))
  (import "brush" "changeBrushThickness" (func $changeBrushThickness (param i32 f64)))
  (import "brush" "setBrushThickness" (func $setBrushThickness (param i32 f64)))
  (import "brush" "changeBrushTransparency" (func $changeBrushTransparency (param i32 f64)))
  (import "brush" "setBrushTransparency" (func $setBrushTransparency (param i32 f64)))
  (import "brush" "startFill" (func $startFill (param i32)))
  (import "brush" "stopFill" (func $stopFill (param i32)))
  (import "brush" "setFillColor" (func $setFillColor (param i32 i32 i32 i32)))
  (import "brush" "notifyPosition" (func $brushNotifyPosition (param i32 f64 f64)))


  ;; ===== MEMORY =====
  (memory (export "memory") 2)
  
  ;; System state offsets
  ;; 0: frame count (i32)
  ;; 4: running (i32)
  ;; 8: current time ms (f64)
  ;; 16: mouse x (f64)
  ;; 24: mouse y (f64)
  ;; 32: mouse clicked (i32)
  ;; 36: key states base (64 bytes for 512 keys as bits)


  ;; ===== GLOBALS =====
  (global $frameCount (mut i32) (i32.const 0))
  (global $running (mut i32) (i32.const 0))
  (global $deltaTime (mut f64) (f64.const 0.016666))
  (global $currentEntityIndex (mut i32) (i32.const 0))
  (global $currentScene (mut i32) (i32.const 0))
  (global $sceneCount (mut i32) (i32.const 1))
  (global $sceneJustChanged (mut i32) (i32.const 0))
  (global $thread_0_pc (mut i32) (i32.const 0))
  (global $thread_0_waiting (mut f64) (f64.const 0))
  (global $thread_0_active (mut i32) (i32.const 0))


  ;; ===== ENTITY ACCESSOR FUNCTIONS =====
  
  ;; Get entity base offset: 1024 + entityIndex * 72
  (func $getEntityOffset (param $idx i32) (result i32)
    (i32.add
      (i32.const 1024)
      (i32.mul (local.get $idx) (i32.const 72))))
  
  ;; Entity property getters/setters
  ;; X position (offset 0)
  (func $getX (param $idx i32) (result f64)
    (f64.load (call $getEntityOffset (local.get $idx))))
  
  (func $setX (param $idx i32) (param $val f64)
    (f64.store (call $getEntityOffset (local.get $idx)) (local.get $val)))
  
  ;; Y position (offset 8)
  (func $getY (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 8))))
  
  (func $setY (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 8)) (local.get $val)))
  
  ;; Rotation (offset 16)
  (func $getRotation (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 16))))
  
  (func $setRotation (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 16)) (local.get $val)))
  
  ;; Direction (offset 24)
  (func $getDirection (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 24))))
  
  (func $setDirection (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 24)) (local.get $val)))
  
  ;; ScaleX (offset 32)
  (func $getScaleX (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 32))))
  
  (func $setScaleX (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 32)) (local.get $val)))
  
  ;; ScaleY (offset 40)
  (func $getScaleY (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 40))))
  
  (func $setScaleY (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 40)) (local.get $val)))
  
  ;; Size (offset 48) - unified scale
  (func $getSize (param $idx i32) (result f64)
    (f64.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 48))))
  
  (func $setSize (param $idx i32) (param $val f64)
    (f64.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 48)) (local.get $val)))
  
  ;; Visible (offset 56, i32)
  (func $getVisible (param $idx i32) (result i32)
    (i32.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 56))))
  
  (func $setVisible (param $idx i32) (param $val i32)
    (i32.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 56)) (local.get $val)))
  
  ;; Picture index (offset 60, i32)
  (func $getPictureIndex (param $idx i32) (result i32)
    (i32.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 60))))
  
  (func $setPictureIndex (param $idx i32) (param $val i32)
    (i32.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 60)) (local.get $val)))
  
  ;; Scene index (offset 64, i32) - which scene this entity belongs to
  (func $getSceneIndex (param $idx i32) (result i32)
    (i32.load (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 64))))
  
  (func $setSceneIndex (param $idx i32) (param $val i32)
    (i32.store (i32.add (call $getEntityOffset (local.get $idx)) (i32.const 64)) (local.get $val)))
  
  ;; Helper: Move in direction
  (func $moveInDirection (param $idx i32) (param $distance f64)
    (local $angle f64)
    (local $rad f64)
    ;; angle = rotation + direction - 90
    (local.set $angle 
      (f64.sub
        (f64.add (call $getRotation (local.get $idx)) (call $getDirection (local.get $idx)))
        (f64.const 90)))
    ;; rad = angle * PI / 180
    (local.set $rad (f64.mul (local.get $angle) (f64.const 0.017453292519943295)))
    ;; x += distance * cos(rad)
    (call $setX (local.get $idx)
      (f64.add (call $getX (local.get $idx))
        (f64.mul (local.get $distance) (call $cos (local.get $rad)))))
    ;; y -= distance * sin(rad)
    (call $setY (local.get $idx)
      (f64.sub (call $getY (local.get $idx))
        (f64.mul (local.get $distance) (call $sin (local.get $rad))))))


  ;; ===== BLOCK HELPER FUNCTIONS =====
  
  ;; Get mouse X from memory
  (func $getMouseX (result f64)
    (f64.load (i32.const 16)))
  
  ;; Get mouse Y from memory
  (func $getMouseY (result f64)
    (f64.load (i32.const 24)))
  
  ;; Check if mouse is clicked
  (func $isMouseClicked (result i32)
    (i32.load (i32.const 32)))
  
  ;; Check if key is pressed (keycode 0-511)
  (func $isKeyPressed (param $keycode i32) (result i32)
    (local $byteOffset i32)
    (local $bitOffset i32)
    (local.set $byteOffset (i32.add (i32.const 36) (i32.shr_u (local.get $keycode) (i32.const 3))))
    (local.set $bitOffset (i32.and (local.get $keycode) (i32.const 7)))
    (i32.and
      (i32.shr_u (i32.load8_u (local.get $byteOffset)) (local.get $bitOffset))
      (i32.const 1)))
  
  ;; Get variable value
  (func $getVariable (param $varOffset i32) (result f64)
    (f64.load (local.get $varOffset)))
  
  ;; Set variable value
  (func $setVariable (param $varOffset i32) (param $val f64)
    (f64.store (local.get $varOffset) (local.get $val)))
  
  ;; Random number between min and max
  (func $randomRange (param $min f64) (param $max f64) (result f64)
    (f64.add
      (local.get $min)
      (f64.mul
        (call $random)
        (f64.sub (local.get $max) (local.get $min)))))
  
  ;; Random integer between min and max (inclusive)
  (func $randomInt (param $min f64) (param $max f64) (result f64)
    (call $floor
      (f64.add
        (local.get $min)
        (f64.mul
          (call $random)
          (f64.add (f64.sub (local.get $max) (local.get $min)) (f64.const 1))))))
  
  ;; ===== SCENE FUNCTIONS =====
  
  ;; Get current scene index
  (func $getCurrentScene (result i32)
    (global.get $currentScene))
  
  ;; Get scene count
  (func $getSceneCount (result i32)
    (global.get $sceneCount))
  
  ;; Update visibility of all entities based on current scene
  (func $updateSceneVisibility
    (local $i i32)
    (local $entityCount i32)
    (local.set $entityCount (i32.const 2))
    (local.set $i (i32.const 0))
    (block $break
      (loop $loop
        (br_if $break (i32.ge_u (local.get $i) (local.get $entityCount)))
        ;; Set visible = 1 if entity's sceneIndex == currentScene, else 0
        (call $setVisible (local.get $i)
          (i32.eq (call $getSceneIndex (local.get $i)) (global.get $currentScene)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop))))
  
  ;; Start a specific scene by index
  (func $startScene (param $sceneIdx i32)
    ;; Bounds check
    (if (i32.and
          (i32.ge_s (local.get $sceneIdx) (i32.const 0))
          (i32.lt_s (local.get $sceneIdx) (global.get $sceneCount)))
      (then
        ;; Only change if different scene
        (if (i32.ne (local.get $sceneIdx) (global.get $currentScene))
          (then
            (global.set $currentScene (local.get $sceneIdx))
            (global.set $sceneJustChanged (i32.const 1))
            (call $updateSceneVisibility))))))
  
  ;; Start neighbor scene (offset: 1 for next, -1 for prev)
  (func $startNeighborScene (param $offset i32)
    (local $newScene i32)
    (local.set $newScene (i32.add (global.get $currentScene) (local.get $offset)))
    ;; Bounds check
    (if (i32.and
          (i32.ge_s (local.get $newScene) (i32.const 0))
          (i32.lt_s (local.get $newScene) (global.get $sceneCount)))
      (then
        (global.set $currentScene (local.get $newScene))
        (global.set $sceneJustChanged (i32.const 1))
        (call $updateSceneVisibility))))
  
  ;; ===== COLLISION DETECTION FUNCTIONS =====
  
  ;; Check if entity touches any edge (simple bounds check)
  (func $isTouchingEdge (param $idx i32) (result i32)
    (local $x f64)
    (local $y f64)
    (local.set $x (call $getX (local.get $idx)))
    (local.set $y (call $getY (local.get $idx)))
    (i32.or
      (i32.or
        (f64.le (local.get $x) (f64.const -240))
        (f64.ge (local.get $x) (f64.const 240)))
      (i32.or
        (f64.le (local.get $y) (f64.const -135))
        (f64.ge (local.get $y) (f64.const 135)))))
  
  ;; Check if entity touches top edge
  (func $isTouchingEdgeTop (param $idx i32) (result i32)
    (f64.ge (call $getY (local.get $idx)) (f64.const 135)))
  
  ;; Check if entity touches bottom edge
  (func $isTouchingEdgeBottom (param $idx i32) (result i32)
    (f64.le (call $getY (local.get $idx)) (f64.const -135)))
  
  ;; Check if entity touches left edge
  (func $isTouchingEdgeLeft (param $idx i32) (result i32)
    (f64.le (call $getX (local.get $idx)) (f64.const -240)))
  
  ;; Check if entity touches right edge
  (func $isTouchingEdgeRight (param $idx i32) (result i32)
    (f64.ge (call $getX (local.get $idx)) (f64.const 240)))
  
  ;; Check if entity touches mouse position (distance-based)
  (func $isTouchingMouse (param $idx i32) (result i32)
    (local $dx f64)
    (local $dy f64)
    (local.set $dx (f64.sub (call $getX (local.get $idx)) (call $getMouseX)))
    (local.set $dy (f64.sub (call $getY (local.get $idx)) (call $getMouseY)))
    ;; Check if distance < 50 (simple approximation)
    (f64.lt
      (f64.add (f64.mul (local.get $dx) (local.get $dx)) (f64.mul (local.get $dy) (local.get $dy)))
      (f64.const 2500)))
  
  ;; Check if two entities touch each other (distance-based)
  (func $isTouchingObject (param $idx1 i32) (param $idx2 i32) (result i32)
    (local $dx f64)
    (local $dy f64)
    (local.set $dx (f64.sub (call $getX (local.get $idx1)) (call $getX (local.get $idx2))))
    (local.set $dy (f64.sub (call $getY (local.get $idx1)) (call $getY (local.get $idx2))))
    ;; Check if distance < 50 (simple approximation)
    (f64.lt
      (f64.add (f64.mul (local.get $dx) (local.get $dx)) (f64.mul (local.get $dy) (local.get $dy)))
      (f64.const 2500)))
  
  ;; Check if object is clicked (stub - returns mouse clicked state for simplicity)
  (func $isObjectClicked (param $idx i32) (result i32)
    (i32.and
      (call $isMouseClicked)
      (call $isTouchingMouse (local.get $idx))))
  
  ;; ===== DIALOG FUNCTIONS =====
  
  ;; Show dialog (calls JS import)
  (func $showDialog (param $idx i32) (param $type i32))
  
  ;; Note: Brush/drawing functions are imported from JS for optimal performance
  ;; See imports section above


  ;; ===== THREAD EXECUTION FUNCTIONS =====
  
  ;; Thread 0: when_run_button_click for entity 0
  (func $thread_0_run (param $entityIdx i32) (result i32)
    (local $pc i32)
    (local $temp f64)
    (local $iterCount i32)
    (local $condResult i32)
    
    ;; Get current program counter
    (local.set $pc (global.get $thread_0_pc))
    
    ;; Check if waiting
    (if (f64.gt (global.get $thread_0_waiting) (f64.const 0))
      (then
        (global.set $thread_0_waiting
          (f64.sub (global.get $thread_0_waiting) (global.get $deltaTime)))
        (return (i32.const 1))))  ;; Still running
    
    ;; Execute based on PC
    (block $end
      (block $done
        (block $pc_0
          (br_if $pc_0 (i32.ne (local.get $pc) (i32.const 0)))
          ;; start_drawing
          (call $startDrawing (i32.const 0))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_0_pc (local.get $pc))
          (br $done))
        (block $pc_1
          (br_if $pc_1 (i32.ne (local.get $pc) (i32.const 1)))
          ;; repeat_basic (simplified - runs inner blocks once per tick)
          ;; Full loop implementation requires coroutine support
          
          ;; move_direction
          (call $moveInDirection (i32.const 0) (f64.const 10))
          (call $brushNotifyPosition (i32.const 0) (call $getX (i32.const 0)) (call $getY (i32.const 0)))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_0_pc (local.get $pc))
          (br $done))
        (block $pc_2
          (br_if $pc_2 (i32.ne (local.get $pc) (i32.const 2)))
          ;; start_fill
          (call $startFill (i32.const 0))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_0_pc (local.get $pc))
          (br $done))
        (block $pc_3
          (br_if $pc_3 (i32.ne (local.get $pc) (i32.const 3)))
          ;; move_y
          (call $setY (i32.const 0)
            (f64.add (call $getY (i32.const 0)) (f64.const -100)))
          (call $brushNotifyPosition (i32.const 0) (call $getX (i32.const 0)) (call $getY (i32.const 0)))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_0_pc (local.get $pc))
          (br $done))
        (block $pc_4
          (br_if $pc_4 (i32.ne (local.get $pc) (i32.const 4)))
          ;; move_x
          (call $setX (i32.const 0)
            (f64.add (call $getX (i32.const 0)) (f64.const -100)))
          (call $brushNotifyPosition (i32.const 0) (call $getX (i32.const 0)) (call $getY (i32.const 0)))
          (local.set $pc (i32.add (local.get $pc) (i32.const 1)))
          (global.set $thread_0_pc (local.get $pc))
          (br $done))
        ;; End of thread
        (global.set $thread_0_pc (i32.const 0))
        (return (i32.const 0))  ;; Thread finished
      )  ;; $done
    )  ;; $end
    
    (i32.const 1)  ;; Thread still running
  )


  ;; ===== MAIN LOOP =====
  
  ;; Initialize entities with their starting values
  (func $init
    ;; Reset scene to first scene
    (global.set $currentScene (i32.const 0))
    (global.set $sceneJustChanged (i32.const 0))
    
    ;; Initialize entity 0: 엔트리봇 (scene: 0)
    (call $setX (i32.const 0) (f64.const 0))
    (call $setY (i32.const 0) (f64.const 0))
    (call $setRotation (i32.const 0) (f64.const 0))
    (call $setDirection (i32.const 0) (f64.const 90))
    (call $setScaleX (i32.const 0) (f64.const 0.5128205128205128))
    (call $setScaleY (i32.const 0) (f64.const 0.5128205128205128))
    (call $setSize (i32.const 0) (f64.const 51.28205128205128))
    (call $setVisible (i32.const 0) (i32.const 1))
    (call $setPictureIndex (i32.const 0) (i32.const 0))
    (call $setSceneIndex (i32.const 0) (i32.const 0))
    ;; Initialize entity 1: 단색 배경 (scene: 0)
    (call $setX (i32.const 1) (f64.const 0))
    (call $setY (i32.const 1) (f64.const 0))
    (call $setRotation (i32.const 1) (f64.const 0))
    (call $setDirection (i32.const 1) (f64.const 90))
    (call $setScaleX (i32.const 1) (f64.const 0.5))
    (call $setScaleY (i32.const 1) (f64.const 0.5))
    (call $setSize (i32.const 1) (f64.const 50))
    (call $setVisible (i32.const 1) (i32.const 1))
    (call $setPictureIndex (i32.const 1) (i32.const 0))
    (call $setSceneIndex (i32.const 1) (i32.const 0))
    
    (global.set $running (i32.const 1)))
  
  ;; Main tick function - called every frame from JS
  (func $tick (param $dt f64)
    (global.set $deltaTime (local.get $dt))
    
    ;; Handle scene change events (when_scene_start)
    
    
    ;; Reset scene changed flag after processing
    (global.set $sceneJustChanged (i32.const 0))
    
    ;; Check events and activate threads
    
    ;; Activate thread 0 on start (entity scene: 0)
    (if (i32.and
          (i32.eqz (global.get $frameCount))
          (i32.eq (i32.const 0) (global.get $currentScene)))
      (then (global.set $thread_0_active (i32.const 1))))
    
    ;; Execute active threads
    
    ;; Run thread 0
    (if (global.get $thread_0_active)
      (then
        (if (i32.eqz (call $thread_0_run (i32.const 0)))
          (then (global.set $thread_0_active (i32.const 0))))))
    
    ;; Increment frame counter
    (global.set $frameCount (i32.add (global.get $frameCount) (i32.const 1))))
  
  ;; Stop execution
  (func $stop
    (global.set $running (i32.const 0)))
  
  ;; Get entity count
  (func $getEntityCount (result i32)
    (i32.const 2))


  ;; ===== EXPORTS =====
  (export "init" (func $init))
  (export "tick" (func $tick))
  (export "stop" (func $stop))
  (export "getEntityCount" (func $getEntityCount))
  (export "getX" (func $getX))
  (export "getY" (func $getY))
  (export "getRotation" (func $getRotation))
  (export "getDirection" (func $getDirection))
  (export "getScaleX" (func $getScaleX))
  (export "getScaleY" (func $getScaleY))
  (export "getSize" (func $getSize))
  (export "getVisible" (func $getVisible))
  (export "getPictureIndex" (func $getPictureIndex))
  (export "getSceneIndex" (func $getSceneIndex))
  (export "getCurrentScene" (func $getCurrentScene))
  (export "getSceneCount" (func $getSceneCount))
  (export "startScene" (func $startScene))
  (export "startNeighborScene" (func $startNeighborScene))
)