#!/usr/bin/env node
/**
 * EntryJS Compiler - Browser Bundle Builder
 *
 * Bundles all compiler modules (parser, WAT generator, block transpiler,
 * renderer generator, and all block handlers) into a single self-contained
 * JavaScript file for use in the browser.
 *
 * Usage:
 *   node compiler/browser/build.js [output-path]
 *
 * Output: compiler/dist/entry-compiler.js (default)
 *
 * The bundle exposes window.EntryCompiler with:
 *   EntryCompiler.compile(projectJson) → { wat, rendererCode, project }
 *   EntryCompiler.run(canvas, projectJson, options) → Promise<API>
 */

const fs = require('fs');
const path = require('path');

const COMPILER_DIR = path.join(__dirname, '..');

// All modules to include in the bundle.
// id: module identifier used in resolved require() calls
// file: path relative to compiler/
const MODULES = [
    // Block handlers (leaf modules, no internal dependencies)
    { id: 'codegen/blocks/movement', file: 'codegen/blocks/movement.js' },
    { id: 'codegen/blocks/looks', file: 'codegen/blocks/looks.js' },
    { id: 'codegen/blocks/flow', file: 'codegen/blocks/flow.js' },
    { id: 'codegen/blocks/variable', file: 'codegen/blocks/variable.js' },
    { id: 'codegen/blocks/calc', file: 'codegen/blocks/calc.js' },
    { id: 'codegen/blocks/judgement', file: 'codegen/blocks/judgement.js' },
    { id: 'codegen/blocks/sound', file: 'codegen/blocks/sound.js' },
    { id: 'codegen/blocks/event', file: 'codegen/blocks/event.js' },
    { id: 'codegen/blocks/brush', file: 'codegen/blocks/brush.js' },
    { id: 'codegen/blocks/func', file: 'codegen/blocks/func.js' },
    { id: 'codegen/blocks/text', file: 'codegen/blocks/text.js' },
    // Block registry (depends on block handlers above)
    { id: 'codegen/blocks/index', file: 'codegen/blocks/index.js' },
    // Block transpiler (depends on blocks/index)
    { id: 'codegen/block-transpiler', file: 'codegen/block-transpiler.js' },
    // WAT generator (depends on block-transpiler)
    { id: 'codegen/wat-generator', file: 'codegen/wat-generator.js' },
    // Renderer generator (no internal dependencies)
    { id: 'codegen/renderer-generator', file: 'codegen/renderer-generator.js' },
    // Parser (no internal dependencies)
    { id: 'parser', file: 'parser.js' },
    // Browser entry point (depends on parser, wat-generator, renderer-generator)
    { id: 'browser/entry', file: 'browser/entry.js' },
];

// Build lookup set for module ID resolution
const moduleIdSet = new Set(MODULES.map(m => m.id));

/**
 * Resolve a require path relative to the requiring module's directory
 * @param {string} fromId - Module ID of the requiring module
 * @param {string} reqPath - The require() argument (e.g. './blocks', '../parser')
 * @returns {string|null} Resolved module ID, or null if external
 */
function resolveRequire(fromId, reqPath) {
    // Skip non-relative paths (external modules like 'fs', 'path')
    if (!reqPath.startsWith('.')) return null;

    const fromDir = path.posix.dirname(fromId);
    let resolved = path.posix.join(fromDir, reqPath).replace(/\.js$/, '');

    // Direct match
    if (moduleIdSet.has(resolved)) return resolved;

    // Directory with index.js
    if (moduleIdSet.has(resolved + '/index')) return resolved + '/index';

    console.warn(`[Build] WARNING: Could not resolve require('${reqPath}') from '${fromId}' → '${resolved}'`);
    return resolved;
}

/**
 * Process a module: read file, resolve require paths
 */
function processModule(mod) {
    const filePath = path.join(COMPILER_DIR, mod.file);
    let content = fs.readFileSync(filePath, 'utf8');

    // Replace all require() calls with resolved module IDs
    content = content.replace(/require\(\s*['"]([^'"]+)['"]\s*\)/g, function(match, reqPath) {
        const resolved = resolveRequire(mod.id, reqPath);
        if (resolved === null) {
            // External module - return a stub that warns on property access
            return "(new Proxy({}, { get: function(_, p) { if (p === Symbol.toPrimitive || p === 'toString' || p === 'valueOf') return undefined; console.warn('[EntryCompiler] Cannot use external module \"" + reqPath + "\" in browser (accessed .' + String(p) + ')'); return undefined; } }))";
        }
        return "require('" + resolved + "')";
    });

    return content;
}

function build(outputPath) {
    console.log('[Build] Bundling ' + MODULES.length + ' modules...');

    // Process all modules
    var processedModules = MODULES.map(function(mod) {
        return {
            id: mod.id,
            content: processModule(mod)
        };
    });

    // Build the bundle
    var parts = [];

    parts.push('/**');
    parts.push(' * EntryJS Compiler - Browser Bundle');
    parts.push(' * ');
    parts.push(' * Compiles and runs EntryJS projects entirely in the browser.');
    parts.push(' * Generated by: node compiler/browser/build.js');
    parts.push(' * ');
    parts.push(' * External dependencies (load via <script> before this file):');
    parts.push(' *   - PixiJS v7+: https://pixijs.download/v7.3.2/pixi.min.js');
    parts.push(' *   - wabt.js:    https://cdn.jsdelivr.net/npm/wabt@1.0.36/index.js');
    parts.push(' * ');
    parts.push(' * API:');
    parts.push(' *   EntryCompiler.compile(projectJson) → { wat, rendererCode, project }');
    parts.push(' *   EntryCompiler.run(canvas, projectJson, options) → Promise<API>');
    parts.push(' */');
    parts.push('(function(_global) {');
    parts.push('"use strict";');
    parts.push('');
    parts.push('var _modules = {};');
    parts.push('var _cache = {};');
    parts.push('');
    parts.push('function _require(id) {');
    parts.push('  if (_cache[id]) return _cache[id].exports;');
    parts.push('  if (!_modules[id]) throw new Error("[EntryCompiler] Module not found: " + id);');
    parts.push('  var module = _cache[id] = { exports: {} };');
    parts.push('  _modules[id](module, module.exports, _require);');
    parts.push('  return module.exports;');
    parts.push('}');
    parts.push('');

    // Add each module
    for (var i = 0; i < processedModules.length; i++) {
        var mod = processedModules[i];
        parts.push('// ── ' + mod.id + ' ──');
        parts.push('_modules[\'' + mod.id + '\'] = function(module, exports, require) {');
        parts.push(mod.content);
        parts.push('};');
        parts.push('');
    }

    // Entry point and export
    parts.push('// ── Initialize ──');
    parts.push('var _entry = _require(\'browser/entry\');');
    parts.push('_global.EntryCompiler = _entry;');
    parts.push('');
    parts.push('})(typeof window !== \'undefined\' ? window : typeof global !== \'undefined\' ? global : this);');

    var output = parts.join('\n');

    // Write output
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, output);

    var sizeKB = (output.length / 1024).toFixed(1);
    console.log('[Build] Bundle saved to ' + outputPath);
    console.log('[Build] Size: ' + sizeKB + ' KB (' + MODULES.length + ' modules)');
    return outputPath;
}

// CLI
if (require.main === module) {
    var outputPath = process.argv[2] || path.join(COMPILER_DIR, 'dist', 'entry-compiler.js');
    build(outputPath);
}

module.exports = { build: build };
