/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmengine_free: (a: number, b: number) => void;
export const wasmengine_fire_key_event: (a: number, b: number) => void;
export const wasmengine_fire_message_cast: (a: number, b: number, c: number) => void;
export const wasmengine_fire_mouse_click_cancled: (a: number) => void;
export const wasmengine_fire_mouse_clicked: (a: number) => void;
export const wasmengine_fire_object_click: (a: number, b: number) => void;
export const wasmengine_fire_object_click_canceled: (a: number, b: number) => void;
export const wasmengine_fire_scene_start: (a: number) => void;
export const wasmengine_get_debug_info: (a: number, b: number) => void;
export const wasmengine_get_js_actions: (a: number, b: number) => void;
export const wasmengine_get_render_buffer_len: (a: number) => number;
export const wasmengine_get_render_buffer_ptr: (a: number) => number;
export const wasmengine_get_render_data: (a: number, b: number) => void;
export const wasmengine_get_tick: (a: number) => bigint;
export const wasmengine_get_variables: (a: number, b: number) => void;
export const wasmengine_has_pending_js_actions: (a: number) => number;
export const wasmengine_is_busy: (a: number) => number;
export const wasmengine_is_running: (a: number) => number;
export const wasmengine_load_project: (a: number, b: number, c: number, d: number) => void;
export const wasmengine_new: () => number;
export const wasmengine_reset: (a: number) => void;
export const wasmengine_set_variables: (a: number, b: number, c: number) => void;
export const wasmengine_start: (a: number) => void;
export const wasmengine_start_scene: (a: number) => void;
export const wasmengine_stop: (a: number) => void;
export const wasmengine_tick: (a: number) => void;
export const wasmengine_update_keys: (a: number, b: number, c: number) => void;
export const wasmengine_update_mouse: (a: number, b: number, c: number, d: number) => void;
export const init: () => void;
export const __wbindgen_export: (a: number, b: number, c: number) => void;
export const __wbindgen_export2: (a: number, b: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
